// frontend/src/app/pages/project-details/task-details-dialog/task-details-dialog.component.ts
import { Component, Inject, OnInit } from '@angular/core';
import { MAT_DIALOG_DATA, MatDialogRef } from '@angular/material/dialog';
import { Router } from '@angular/router';
import { CommonModule } from '@angular/common';
import { MatDialogModule } from '@angular/material/dialog';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatChipsModule } from '@angular/material/chips';
import { MatMenuModule } from '@angular/material/menu';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { ProjectService } from '../../../services/project.service';

@Component({
  selector: 'app-task-details-dialog',
  standalone: true,
  imports: [
    CommonModule,
    MatDialogModule,
    MatButtonModule,
    MatIconModule,
    MatChipsModule,
    MatMenuModule,
    MatProgressSpinnerModule,
  ],
  templateUrl: './task-details-dialog.component.html',
  styleUrls: ['./task-details-dialog.component.css'],
})
export class TaskDetailsDialogComponent implements OnInit {
  isLoading = true;
  taskDetails: any;

  constructor(
    public dialogRef: MatDialogRef<TaskDetailsDialogComponent>,
    @Inject(MAT_DIALOG_DATA) public data: any,
    private router: Router,
    private projectService: ProjectService
  ) {}

  ngOnInit() {
    this.loadTaskDetails();
  }

  loadTaskDetails() {
    this.isLoading = true;
    this.projectService
      .getTaskDetails(this.data.projectId, this.data.task._id)
      .subscribe({
        next: (details) => {
          this.taskDetails = details;
          this.isLoading = false;
        },
        error: (error) => {
          console.error('Error loading task details:', error);
          this.isLoading = false;
        },
      });
  }

  close(): void {
    this.dialogRef.close();
  }

  viewFullDetails(): void {
    this.dialogRef.close();
    this.router.navigate([
      '/projects',
      this.data.projectId,
      'tasks',
      this.data.task._id,
    ]);
  }

  getStatusClass(status: string): string {
    switch (status) {
      case 'Not Started':
        return 'bg-gray-500 text-gray-100';
      case 'In Progress':
        return 'bg-blue-500 text-gray-100';
      case 'Stuck':
        return 'bg-red-500 text-gray-100';
      case 'Done':
        return 'bg-green-500 text-gray-100';
      default:
        return 'bg-gray-500 text-gray-100';
    }
  }

  getPriorityClass(priority: string): string {
    switch (priority) {
      case 'low':
        return 'bg-green-500 text-gray-100';
      case 'medium':
        return 'bg-yellow-500 text-gray-900';
      case 'high':
        return 'bg-orange-500 text-gray-100';
      case 'critical':
        return 'bg-red-500 text-gray-100';
      default:
        return 'bg-gray-500 text-gray-100';
    }
  }

  getAssignedMembers(): any[] {
    const task = this.taskDetails || this.data.task;
    if (!task || !task.assignedTo) return [];

    return task.assignedTo.map((member: any) => {
      if (typeof member === 'object' && member !== null) {
        return member;
      }
      const projectMember = this.data.projectMembers.find(
        (m: any) => m._id === member
      );
      return projectMember || { _id: member, username: 'Unknown User' };
    });
  }
}

<div class="task-details-dialog w-full max-w-3xl mx-auto overflow-y-auto bg-white dark:bg-gray-800">
  <!-- Loading Overlay -->
  <div *ngIf="isLoading" class="absolute inset-0 bg-white dark:bg-gray-800 bg-opacity-90 dark:bg-opacity-90 z-50 flex items-center justify-center">
    <mat-spinner diameter="40"></mat-spinner>
  </div>

  <!-- Content -->
  <div [class.opacity-50]="isLoading">
    <!-- Header Section -->
    <div class="sticky top-0 bg-white dark:bg-gray-800 z-10 p-4 border-b border-gray-200 dark:border-gray-700">
      <div class="flex justify-between items-start gap-4">
        <div class="flex-1 min-w-0">
          <h2 class="text-xl sm:text-2xl font-bold text-gray-800 dark:text-gray-100 mb-2 truncate">
            {{ taskDetails?.title || data.task.title }}
          </h2>
          <div class="flex flex-wrap items-center gap-2">
            <span
              [class]="getStatusClass(taskDetails?.status || data.task.status)"
              class="px-2 sm:px-3 py-1 rounded-full text-xs sm:text-sm font-semibold whitespace-nowrap"
            >
              {{ taskDetails?.status || data.task.status }}
            </span>
            <span
              [class]="getPriorityClass(taskDetails?.priority || data.task.priority)"
              class="px-2 sm:px-3 py-1 rounded-full text-xs sm:text-sm font-semibold whitespace-nowrap"
            >
              {{ taskDetails?.priority || data.task.priority }}
            </span>
          </div>
        </div>
        <button
          mat-icon-button
          (click)="close()"
          class="text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-200 flex-shrink-0"
        >
          <mat-icon>close</mat-icon>
        </button>
      </div>
    </div>

    <!-- Main Content -->
    <div class="p-4">
      <!-- Description Section -->
      <div class="mb-6">
        <h3 class="text-xs sm:text-sm font-semibold text-gray-700 dark:text-gray-300 mb-2 uppercase tracking-wider">
          Description
        </h3>
        <div class="bg-gray-50 dark:bg-gray-700 p-3 sm:p-4 rounded-lg">
          <p class="text-sm sm:text-base text-gray-600 dark:text-gray-300 break-words">
            {{ taskDetails?.description || data.task.description }}
          </p>
        </div>
      </div>

      <!-- Info Grid -->
      <div class="grid grid-cols-1 sm:grid-cols-2 gap-4 sm:gap-6">
        <!-- Timeline Section -->
        <div>
          <h3
            class="text-xs sm:text-sm font-semibold text-gray-700 dark:text-gray-300 mb-2 uppercase tracking-wider"
          >
            Timeline
          </h3>
          <div class="bg-gray-50 dark:bg-gray-700 p-3 sm:p-4 rounded-lg space-y-2">
            <div class="flex items-center gap-2">
              <mat-icon class="text-gray-400 dark:text-gray-500 text-sm">calendar_today</mat-icon>
              <span class="text-xs sm:text-sm text-gray-600 dark:text-gray-300">
                Start: {{ taskDetails?.timeline?.start || data.task.timeline?.start | date : "mediumDate" }}
              </span>
            </div>
            <div class="flex items-center gap-2">
              <mat-icon class="text-gray-400 dark:text-gray-500 text-sm">event</mat-icon>
              <span class="text-xs sm:text-sm text-gray-600 dark:text-gray-300">
                End: {{ taskDetails?.timeline?.end || data.task.timeline?.end | date : "mediumDate" }}
              </span>
            </div>
          </div>
        </div>

        <!-- Assigned Members Section -->
        <div>
          <h3
            class="text-xs sm:text-sm font-semibold text-gray-700 dark:text-gray-300 mb-2 uppercase tracking-wider"
          >
            Assigned Members
          </h3>
          <div class="bg-gray-50 dark:bg-gray-700 p-3 sm:p-4 rounded-lg">
            <div class="flex flex-col gap-2">
              <div
                *ngFor="let member of getAssignedMembers()"
                class="flex items-center justify-between bg-white dark:bg-gray-800 p-2 rounded-lg border border-gray-200 dark:border-gray-700 hover:border-blue-400 dark:hover:border-blue-500 transition-colors"
              >
                <div class="flex items-center gap-3">
                  <img
                    [src]="
                      'https://ui-avatars.com/api/?name=' +
                      member.username +
                      '&background=random'
                    "
                    [alt]="member.username"
                    class="w-8 h-8 rounded-full"
                  />
                  <span class="text-sm text-gray-700 dark:text-gray-300 font-medium">{{
                    member.username
                  }}</span>
                </div>
                <span class="text-xs text-gray-500 dark:text-gray-400 bg-gray-100 dark:bg-gray-700 px-2 py-1 rounded"
                  >Member</span
                >
              </div>
              <div
                *ngIf="getAssignedMembers().length === 0"
                class="text-gray-500 text-sm italic p-2 text-center"
              >
                No members assigned
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Footer Actions -->
    <div
      class="sticky bottom-0 bg-white dark:bg-gray-800 border-t border-gray-200 dark:border-gray-700 p-4 flex justify-end gap-3"
    >
      <button
        mat-button
        class="text-gray-600 dark:text-gray-300 text-sm sm:text-base"
        (click)="close()"
        [disabled]="isLoading"
      >
        Close
      </button>
      <button
        mat-raised-button
        color="primary"
        class="px-4 sm:px-6 text-sm sm:text-base dark:bg-blue-600 dark:text-white dark:hover:bg-blue-700"
        (click)="viewFullDetails()"
        [disabled]="isLoading"
      >
        View Full Details
      </button>
    </div>
  </div>
</div>

// frontend-react/src/pages/project-details/TaskDetailsDialog.tsx
import { Modal, Spin, Button } from "antd";
import { useEffect, useState } from "react";
import { projectService } from "../../services/api/projectService";
import { CloseOutlined } from '@ant-design/icons';
import { useNavigate } from 'react-router-dom';

interface TaskDetailsDialogProps {
  open: boolean;
  projectId: string | undefined;
  task: any;
  projectMembers: any[];
  onClose: () => void;
}

const TaskDetailsDialog = ({
  open,
  projectId,
  task,
  projectMembers,
  onClose,
}: TaskDetailsDialogProps) => {
  const [isLoading, setIsLoading] = useState(true);
  const [taskDetails, setTaskDetails] = useState<any>(null);
  const navigate = useNavigate();

  useEffect(() => {
    if (open && projectId && task) {
      loadTaskDetails();
    }
  }, [open, projectId, task]);

  const loadTaskDetails = async () => {
    if (!projectId || !task._id) return;

    try {
      setIsLoading(true);
      const details = await projectService.getTaskDetails(projectId, task._id);
      setTaskDetails(details);
    } catch (error) {
      console.error("Error loading task details:", error);
    } finally {
      setIsLoading(false);
    }
  };

  const getStatusClass = (status: string): string => {
    switch (status) {
      case "Not Started":
        return "bg-gray-500 text-gray-100";
      case "In Progress":
        return "bg-blue-500 text-gray-100";
      case "Stuck":
        return "bg-red-500 text-gray-100";
      case "Done":
        return "bg-green-500 text-gray-100";
      default:
        return "bg-gray-500 text-gray-100";
    }
  };

  const getPriorityClass = (priority: string): string => {
    switch (priority.toLowerCase()) {
      case "low":
        return "bg-green-500 text-white";
      case "medium":
        return "bg-yellow-500 text-white";
      case "high":
        return "bg-orange-500 text-white";
      case "critical":
        return "bg-red-500 text-white";
      default:
        return "bg-gray-500 text-white";
    }
  };

  const getAssignedMembers = () => {
    const currentTask = taskDetails || task;
    if (!currentTask || !currentTask.assignedTo) return [];

    return currentTask.assignedTo.map((member: any) => {
      if (typeof member === "object" && member !== null) {
        return member;
      }
      const projectMember = projectMembers.find((m: any) => m._id === member);
      return projectMember || { _id: member, username: "Unknown User" };
    });
  };

  const handleViewFullDetails = () => {
    onClose();
    navigate(`/projects/${projectId}/tasks/${task._id}`);
  };

  return (
    <Modal
      open={open}
      onCancel={onClose}
      footer={null}
      width={800}
      closeIcon={null}
      styles={{
        body: {
          maxHeight: "80vh",
          overflow: "auto",
          padding: 0,
          backgroundColor: "transparent",
        },
        mask: {
          backgroundColor: "rgba(0, 0, 0, 0.6)",
        },
        content: {
          backgroundColor: "transparent",
          boxShadow: "none",
        },
        wrapper: {
          backgroundColor: "transparent",
        },
      }}
      className="task-details-dialog"
    >
      <div className="w-full max-w-3xl mx-auto overflow-y-auto bg-white dark:bg-gray-800 rounded-lg shadow-xl">
        {isLoading ? (
          <div className="absolute inset-0 bg-white/90 dark:bg-gray-800/90 z-50 flex items-center justify-center rounded-lg">
            <Spin size="large" />
          </div>
        ) : (
          <div className={isLoading ? "opacity-50" : ""}>
            <div className="sticky top-0 bg-white dark:bg-gray-800 z-10 p-4 border-b border-gray-200 dark:border-gray-700 rounded-t-lg">
              <div className="flex justify-between items-start gap-4">
                <div className="flex-1 min-w-0">
                  <h2 className="text-xl sm:text-2xl font-bold text-gray-900 dark:text-white mb-2 truncate">
                    {taskDetails?.title || task.title}
                  </h2>
                  <div className="flex flex-wrap items-center gap-2">
                    <span
                      className={`${getStatusClass(
                        taskDetails?.status || task.status
                      )} px-2 sm:px-3 py-1 rounded-full text-xs sm:text-sm font-semibold whitespace-nowrap`}
                    >
                      {taskDetails?.status || task.status}
                    </span>
                    <span
                      className={`${getPriorityClass(
                        taskDetails?.priority || task.priority
                      )} px-2 sm:px-3 py-1 rounded-full text-xs sm:text-sm font-semibold whitespace-nowrap`}
                    >
                      {taskDetails?.priority || task.priority}
                    </span>
                  </div>
                </div>
                <Button
                  type="text"
                  onClick={onClose}
                  className="text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-200 -mt-2 -mr-2"
                  icon={<CloseOutlined />}
                />
              </div>
            </div>

            <div className="p-4 bg-white dark:bg-gray-800">
              <div className="mb-6">
                <h3 className="text-xs sm:text-sm font-semibold text-gray-700 dark:text-gray-300 mb-2 uppercase tracking-wider">
                  Description
                </h3>
                <div className="bg-gray-50 dark:bg-gray-700/50 p-3 sm:p-4 rounded-lg">
                  <p className="text-sm sm:text-base text-gray-600 dark:text-gray-300 break-words">
                    {taskDetails?.description ||
                      task.description ||
                      "No description provided"}
                  </p>
                </div>
              </div>

              <div>
                <h3 className="text-xs sm:text-sm font-semibold text-gray-700 dark:text-gray-300 mb-2 uppercase tracking-wider">
                  Assigned Members
                </h3>
                <div className="bg-gray-50 dark:bg-gray-700/50 p-3 sm:p-4 rounded-lg">
                  <div className="flex flex-col gap-2">
                    {getAssignedMembers().map((member: any) => (
                      <div
                        key={member._id}
                        className="flex items-center justify-between bg-white dark:bg-gray-800 p-2 rounded-lg border border-gray-200 dark:border-gray-600 hover:border-blue-400 dark:hover:border-blue-500 transition-colors"
                      >
                        <div className="flex items-center gap-3">
                          <img
                            src={`https://ui-avatars.com/api/?name=${member.username}&background=random`}
                            alt={member.username}
                            className="w-8 h-8 rounded-full"
                          />
                          <span className="text-sm text-gray-700 dark:text-gray-200 font-medium">
                            {member.username}
                          </span>
                        </div>
                        <span className="text-xs text-gray-500 dark:text-gray-400 bg-gray-100 dark:bg-gray-700 px-2 py-1 rounded">
                          Member
                        </span>
                      </div>
                    ))}
                    {getAssignedMembers().length === 0 && (
                      <div className="text-gray-500 dark:text-gray-400 text-sm italic p-2 text-center">
                        No members assigned
                      </div>
                    )}
                  </div>
                </div>
              </div>
            </div>

            <div className="sticky bottom-0 bg-white dark:bg-gray-800 border-t border-gray-200 dark:border-gray-700 p-4 flex justify-end gap-3">
              <Button 
                onClick={onClose}
                className="text-gray-600 dark:text-gray-300"
              >
                Close
              </Button>
              <Button
                type="primary"
                onClick={handleViewFullDetails}
                className="bg-blue-600 hover:bg-blue-700"
              >
                View Full Details
              </Button>
            </div>
          </div>
        )}
      </div>
    </Modal>
  );
};

export default TaskDetailsDialog;
