// frontend-react/src/pages/assigned-tasks/AssignedTasks.tsx
import { useState, useEffect } from 'react';
import { Spin, Select, Button, Card, Tooltip } from 'antd';
import { SortAscendingOutlined, SortDescendingOutlined } from '@ant-design/icons';
import { projectService } from '../../services/api/projectService';
import { useNavigate } from 'react-router-dom';

type SortOption = 'status' | 'priority' | 'title';
type SortDirection = 'asc' | 'desc';
type TaskStatus = 'Not Started' | 'In Progress' | 'Stuck' | 'Done';
type TaskPriority = 'Critical' | 'High' | 'Medium' | 'Low';

interface TasksByProject {
  [projectId: string]: {
    projectName: string;
    tasks: any[];
  };
}

const AssignedTasks = () => {
  const navigate = useNavigate();
  const [isLoading, setIsLoading] = useState(true);
  const [tasksByProject, setTasksByProject] = useState<TasksByProject>({});
  const [sortBy, setSortBy] = useState<SortOption>('status');
  const [sortDirection, setSortDirection] = useState<SortDirection>('asc');

  const sortOptions = [
    { value: 'status', label: 'Status' },
    { value: 'priority', label: 'Priority' },
    { value: 'title', label: 'Title' }
  ];

  useEffect(() => {
    loadAssignedTasks();
  }, []);

  const loadAssignedTasks = async () => {
    try {
      setIsLoading(true);
      const tasks = await projectService.getAssignedTasks();
      organizeTasksByProject(tasks);
    } catch (error) {
      console.error('Error loading assigned tasks:', error);
    } finally {
      setIsLoading(false);
    }
  };

  const organizeTasksByProject = (tasks: any[]) => {
    const organized = tasks.reduce((acc, task) => {
      if (!acc[task.projectId]) {
        acc[task.projectId] = {
          projectName: task.projectName,
          tasks: [],
        };
      }
      acc[task.projectId].tasks.push(task);
      return acc;
    }, {} as TasksByProject);

    setTasksByProject(organized);
    sortTasks(organized);
  };

  const compareStatus = (a: string, b: string): number => {
    const statusOrder: Record<TaskStatus, number> = {
      'Not Started': 0,
      'In Progress': 1,
      'Stuck': 2,
      'Done': 3
    };
    return (statusOrder[a as TaskStatus] ?? 0) - (statusOrder[b as TaskStatus] ?? 0);
  };

  const comparePriority = (a: string, b: string): number => {
    const priorityOrder: Record<string, number> = {
      'critical': 0,
      'high': 1,
      'medium': 2,
      'low': 3
    };
    return (priorityOrder[a.toLowerCase()] ?? 999) - (priorityOrder[b.toLowerCase()] ?? 999);
  };

  const sortTasks = (currentTasks: TasksByProject = tasksByProject) => {
    const sorted = Object.entries(currentTasks).reduce((acc, [projectId, project]) => {
      const sortedTasks = [...project.tasks].sort((a, b) => {
        let comparison = 0;
        switch (sortBy) {
          case 'status':
            comparison = compareStatus(a.status, b.status);
            break;
          case 'priority':
            comparison = comparePriority(a.priority, b.priority);
            break;
          case 'title':
            comparison = a.title.localeCompare(b.title);
            break;
        }
        return sortDirection === 'asc' ? comparison : -comparison;
      });

      acc[projectId] = {
        ...project,
        tasks: sortedTasks
      };
      return acc;
    }, {} as TasksByProject);

    setTasksByProject(sorted);
  };

  const getStatusClass = (status: string): string => {
    switch (status) {
      case 'Not Started':
        return 'bg-gray-500 text-white';
      case 'In Progress':
        return 'bg-blue-500 text-white';
      case 'Stuck':
        return 'bg-red-500 text-white';
      case 'Done':
        return 'bg-green-500 text-white';
      default:
        return 'bg-gray-500 text-white';
    }
  };

  const getPriorityClass = (priority: string): string => {
    switch (priority.toLowerCase()) {
      case 'low':
        return 'bg-green-500 text-white';
      case 'medium':
        return 'bg-yellow-500 text-white';
      case 'high':
        return 'bg-orange-500 text-white';
      case 'critical':
        return 'bg-purple-500 text-white';
      default:
        return 'bg-gray-500 text-white';
    }
  };

  if (isLoading) {
    return (
      <div className="flex justify-center items-center min-h-screen">
        <Spin size="large" />
      </div>
    );
  }

  return (
    <div className="bg-gray-100 dark:bg-gray-900 min-h-screen p-4 sm:p-6">
      <div className="max-w-7xl mx-auto">
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-sm p-4 sm:p-6 mb-6">
          <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
            <h2 className="text-2xl font-bold text-gray-800 dark:text-gray-100">
              Tasks Assigned to You
            </h2>

            <div className="flex items-center gap-4 w-full sm:w-auto">
              <Select
                className="w-full sm:w-48"
                value={sortBy}
                onChange={(value) => {
                  setSortBy(value as SortOption);
                  sortTasks();
                }}
                options={sortOptions}
              />

              <Tooltip title={`Sort ${sortDirection === 'asc' ? 'Ascending' : 'Descending'}`}>
                <Button
                  icon={sortDirection === 'asc' ? <SortAscendingOutlined /> : <SortDescendingOutlined />}
                  onClick={() => {
                    setSortDirection(sortDirection === 'asc' ? 'desc' : 'asc');
                    sortTasks();
                  }}
                />
              </Tooltip>
            </div>
          </div>

          {/* Task Statistics */}
          <div className="mt-6 grid grid-cols-2 sm:grid-cols-5 gap-4">
            {/* Add task statistics components here */}
          </div>
        </div>

        {/* Project Tasks */}
        {Object.entries(tasksByProject).map(([projectId, project]) => (
          <div key={projectId} className="bg-white dark:bg-gray-800 rounded-lg shadow-sm mb-6">
            <div className="p-4 border-b border-gray-200 dark:border-gray-700">
              <h3 className="text-xl font-semibold text-gray-800 dark:text-gray-100">
                {project.projectName}
              </h3>
            </div>
            <div className="p-4 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {project.tasks.map((task) => (
                <Card
                  key={task._id}
                  className="dark:bg-gray-700 hover:shadow-lg transition-shadow"
                  onClick={() => navigate(`/projects/${task.projectId}/tasks/${task._id}`)}
                >
                  <h4 className="text-lg font-semibold mb-2 dark:text-gray-100">{task.title}</h4>
                  <p className="text-gray-600 dark:text-gray-300 mb-4 line-clamp-2">{task.description}</p>
                  <div className="flex justify-between items-center">
                    <span className={`px-3 py-1 rounded-full text-sm ${getStatusClass(task.status)}`}>
                      {task.status}
                    </span>
                    <span className={`px-3 py-1 rounded-full text-sm ${getPriorityClass(task.priority)}`}>
                      {task.priority}
                    </span>
                  </div>
                </Card>
              ))}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default AssignedTasks;

// frontend/src/app/pages/assigned-tasks/assigned-tasks.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatListModule } from '@angular/material/list';
import { MatIconModule } from '@angular/material/icon';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatExpansionModule } from '@angular/material/expansion';
import { MatSelectModule } from '@angular/material/select';
import { MatFormFieldModule } from '@angular/material/form-field';
import { FormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { ProjectService } from '../../services/project.service';
import { MatMenuModule } from '@angular/material/menu';
import { MatSelectChange } from '@angular/material/select';
import { MatTooltipModule } from '@angular/material/tooltip';

interface TasksByProject {
  [projectId: string]: {
    projectName: string;
    tasks: any[];
  };
}

type SortOption = 'status' | 'priority' | 'title';
type SortDirection = 'asc' | 'desc';
type TaskStatus = 'Not Started' | 'In Progress' | 'Stuck' | 'Done';
type TaskPriority = 'Critical' | 'High' | 'Medium' | 'Low';

@Component({
  selector: 'app-assigned-tasks',
  standalone: true,
  imports: [
    CommonModule,
    MatListModule,
    MatIconModule,
    MatCardModule,
    MatButtonModule,
    MatExpansionModule,
    MatSelectModule,
    MatFormFieldModule,
    FormsModule,
    RouterModule,
    MatMenuModule,
    MatTooltipModule,
  ],
  templateUrl: './assigned-tasks.component.html',
  styleUrls: ['./assigned-tasks.component.css'],
})
export class AssignedTasksComponent implements OnInit {
  tasksByProject: TasksByProject = {};
  statuses = ['Not Started', 'In Progress', 'Stuck', 'Done'];
  priorities = ['Critical', 'High', 'Medium', 'Low'];

  sortBy: SortOption = 'status';
  sortDirection: SortDirection = 'asc';

  sortOptions = [
    { value: 'status', label: 'Status', icon: 'list_alt' },
    { value: 'priority', label: 'Priority', icon: 'priority_high' },
    { value: 'title', label: 'Title', icon: 'sort_by_alpha' }
  ];

  constructor(private projectService: ProjectService) { }

  ngOnInit() {
    this.loadAssignedTasks();
  }

  loadAssignedTasks() {
    this.projectService.getAssignedTasks().subscribe({
      next: (tasks) => {
        this.organizeTasksByProject(tasks);
        this.sortTasks();
      },
      error: (error) => {
        console.error('Error loading assigned tasks:', error);
      },
    });
  }

  organizeTasksByProject(tasks: any[]) {
    this.tasksByProject = tasks.reduce((acc, task) => {
      if (!acc[task.projectId]) {
        acc[task.projectId] = {
          projectName: task.projectName,
          tasks: [],
        };
      }
      acc[task.projectId].tasks.push(task);
      return acc;
    }, {});
  }

  sortTasks() {
    Object.values(this.tasksByProject).forEach(project => {
      project.tasks.sort((a, b) => {
        let comparison = 0;

        switch (this.sortBy) {
          case 'status':
            comparison = this.compareStatus(a.status, b.status);
            break;
          case 'priority':
            comparison = this.comparePriority(a.priority, b.priority);
            break;
          case 'title':
            comparison = a.title.localeCompare(b.title);
            break;
        }

        return this.sortDirection === 'asc' ? comparison : -comparison;
      });
    });
  }

  private compareStatus(a: string, b: string): number {
    const statusOrder: Record<TaskStatus, number> = {
      'Not Started': 0,
      'In Progress': 1,
      'Stuck': 2,
      'Done': 3
    };

    return (statusOrder[a as TaskStatus] ?? 0) - (statusOrder[b as TaskStatus] ?? 0);
  }

  private comparePriority(a: string, b: string): number {
    const priorityOrder: Record<string, number> = {
      'critical': 0,
      'high': 1,
      'medium': 2,
      'low': 3
    };

    const priorityA = a.toLowerCase();
    const priorityB = b.toLowerCase();

    return (priorityOrder[priorityA] ?? 999) - (priorityOrder[priorityB] ?? 999);
  }

  onSortChange(event: MatSelectChange) {
    this.sortBy = event.value;
    this.sortTasks();
  }

  toggleSortDirection() {
    this.sortDirection = this.sortDirection === 'asc' ? 'desc' : 'asc';
    this.sortTasks();
  }

  get objectKeys() {
    return Object.keys;
  }

  updateTaskStatus(projectId: string, taskId: string, newStatus: string) {
    this.projectService
      .updateTaskStatus(projectId, taskId, newStatus)
      .subscribe({
        next: (updatedTask) => {
          const task = this.tasksByProject[projectId].tasks.find(
            (t) => t._id === taskId
          );
          if (task) {
            task.status = newStatus;
          }
        },
        error: (error) => {
          console.error('Error updating task status:', error);
        },
      });
  }

  getStatusClass(status: string): string {
    switch (status) {
      case 'Not Started':
        return 'bg-gray-500 text-white';
      case 'In Progress':
        return 'bg-blue-500 text-white';
      case 'Stuck':
        return 'bg-red-500 text-white';
      case 'Done':
        return 'bg-green-500 text-white';
      default:
        return 'bg-gray-500 text-white';
    }
  }

  getPriorityClass(priority: string): string {
    switch (priority.toLowerCase()) {
      case 'low':
        return 'bg-green-500 text-white';
      case 'medium':
        return 'bg-yellow-500 text-white';
      case 'high':
        return 'bg-orange-500 text-white';
      case 'critical':
        return 'bg-purple-500 text-white';
      default:
        return 'bg-gray-500 text-white';
    }
  }

  getSortIcon(sortValue: string): string {
    const iconMap: Record<string, string> = {
      'status': 'list_alt',
      'priority': 'priority_high',
      'title': 'sort_by_alpha'
    };
    return iconMap[sortValue] || 'sort';
  }

  getTotalTasks(): number {
    return Object.values(this.tasksByProject).reduce(
      (total, project) => total + project.tasks.length, 
      0
    );
  }

  getCompletedTasks(): number {
    return Object.values(this.tasksByProject).reduce(
      (total, project) => total + project.tasks.filter(
        task => task.status === 'Done'
      ).length, 
      0
    );
  }

  getStuckTasks(): number {
    return Object.values(this.tasksByProject).reduce(
      (total, project) => total + project.tasks.filter(
        task => task.status === 'Stuck'
      ).length, 
      0
    );
  }
  getInProgressTasks(): number {
    return Object.values(this.tasksByProject).reduce(
      (total, project) => total + project.tasks.filter(
        task => task.status === 'In Progress'
      ).length, 
      0
    );
  }
  getNotStartedTasks(): number {
    return Object.values(this.tasksByProject).reduce(
      (total, project) => total + project.tasks.filter(
        task => task.status === 'Not Started'
      ).length, 
      0
    );
  }
}

<div class="content max-w-6xl mx-auto p-2 sm:p-4 md:p-6">
  <!-- Header and Sorting Section -->
  <div class="bg-white rounded-lg shadow-sm p-4 mb-6">
    <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
      <!-- Title -->
      <h2 class="text-xl sm:text-2xl md:text-3xl font-bold text-gray-800">
        Tasks Assigned to You
      </h2>

      <!-- Sorting Controls -->
      <div class="flex items-center gap-3 w-full sm:w-auto">
        <mat-form-field appearance="fill" class="w-full sm:w-48 sorting-field">
          <mat-label>Sort by</mat-label>
          <mat-select [value]="sortBy" (selectionChange)="onSortChange($event)" panelClass="sort-select-panel">
            <mat-option *ngFor="let option of sortOptions" [value]="option.value">
              <div class="flex items-center gap-2">

                {{ option.label }}
              </div>
            </mat-option>
          </mat-select>
        </mat-form-field>

        <button mat-icon-button (click)="toggleSortDirection()"
          [matTooltip]="'Sort ' + (sortDirection === 'asc' ? 'Ascending' : 'Descending')" class="sort-direction-btn"
          [ngClass]="{'text-primary': true}">
          <mat-icon class="transform transition-transform duration-200"
            [ngClass]="{'rotate-180': sortDirection === 'desc'}">
            sort
          </mat-icon>
        </button>
      </div>
    </div>

    <!-- Optional: Add summary stats -->
    <div class="mt-4 flex flex-wrap gap-4 text-sm text-gray-600">
      <div class="flex items-center gap-2">
        <mat-icon class="text-gray-400">assignment</mat-icon>
        <span>Total Tasks: {{getTotalTasks()}}</span>
      </div>
      <div class="flex items-center gap-2">
        <mat-icon class="text-green-500">check_circle</mat-icon>
        <span>Completed: {{getCompletedTasks()}}</span>
      </div>
      <div class="flex items-center gap-2">
        <mat-icon class="text-red-500">cancel</mat-icon>
        <span>Stuck: {{getStuckTasks()}}</span>
      </div>
      <div class="flex items-center gap-2">
        <mat-icon class="text-blue-500">pending</mat-icon>
        <span>In Progress: {{getInProgressTasks()}}</span>
      </div>
      <div class="flex items-center gap-2">
        <mat-icon class="text-gray-500">not_started</mat-icon>
        <span>Not Started: {{getNotStartedTasks()}}</span>
      </div>
    </div>
  </div>

  <!-- Existing accordion content -->
  <mat-accordion multi>
    <mat-expansion-panel *ngFor="let projectId of objectKeys(tasksByProject)" [expanded]="true" class="mb-3 sm:mb-4">
      <mat-expansion-panel-header class="bg-gray-100">
        <mat-panel-title class="project-title text-sm sm:text-base md:text-lg font-semibold text-gray-800 truncate">
          {{ tasksByProject[projectId].projectName }}
        </mat-panel-title>
        <!-- <mat-panel-description class="text-xs sm:text-sm md:text-base text-gray-600 whitespace-nowrap">
          {{ tasksByProject[projectId].tasks.length }} tasks
        </mat-panel-description> -->
      </mat-expansion-panel-header>

      <div
        class="task-list grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3 sm:gap-4 md:gap-6 mt-3 sm:mt-4 md:mt-6">
        <mat-card *ngFor="let task of tasksByProject[projectId].tasks" class="task-card flex flex-col h-full">
          <div class="flex justify-between items-start mb-2">
            <mat-card-header class="p-0">
              <mat-card-title class="text-base sm:text-lg md:text-xl font-semibold">{{ task.title }}</mat-card-title>
            </mat-card-header>
            <button mat-icon-button [routerLink]="['/projects', task.projectId, 'tasks', task._id]"
              class="text-blue-600 hover:text-blue-800 transition-colors duration-200 -mt-2 -mr-2"
              aria-label="View task details">
              <mat-icon class="text-sm sm:text-base md:text-lg">visibility</mat-icon>
            </button>
          </div>
          <mat-card-content class="flex-grow mb-2 sm:mb-3">
            <p class="text-xs sm:text-sm md:text-base text-gray-600">{{ task.description }}</p>
          </mat-card-content>
          <div class="task-details mt-auto">
            <div class="flex items-center justify-between">
              <button [matMenuTriggerFor]="statusMenu" [ngClass]="getStatusClass(task.status)"
                class="px-2 py-1 rounded-tl-full rounded-bl-full text-xs sm:text-sm font-medium flex items-center transition-colors duration-200 ease-in-out focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500">
                <span class="mr-1">{{ task.status }}</span>
                <mat-icon class="text-xs sm:text-sm">arrow_drop_down</mat-icon>
              </button>
              <mat-menu #statusMenu="matMenu" class="custom-menu">
                <button mat-menu-item (click)="updateTaskStatus(projectId, task._id, 'Not Started')"
                  class="flex items-center">
                  <span class="w-3 h-3 rounded-full bg-gray-500 mr-3"></span>
                  Not Started
                </button>
                <button mat-menu-item (click)="updateTaskStatus(projectId, task._id, 'In Progress')"
                  class="flex items-center">
                  <span class="w-3 h-3 rounded-full bg-blue-500 mr-3"></span>
                  In Progress
                </button>
                <button mat-menu-item (click)="updateTaskStatus(projectId, task._id, 'Stuck')"
                  class="flex items-center">
                  <span class="w-3 h-3 rounded-full bg-red-500 mr-3"></span>
                  Stuck
                </button>
                <button mat-menu-item (click)="updateTaskStatus(projectId, task._id, 'Done')" class="flex items-center">
                  <span class="w-3 h-3 rounded-full bg-green-500 mr-3"></span>
                  Done
                </button>
              </mat-menu>
              <span [ngClass]="getPriorityClass(task.priority)"
                class="px-3 py-2 sm:py-1.5 rounded-tr-full rounded-br-full text-xs sm:text-sm font-medium">
                {{ task.priority }}
              </span>
            </div>
          </div>
        </mat-card>
      </div>
    </mat-expansion-panel>
  </mat-accordion>
</div>
