// frontend-react/src/pages/task-details/TaskDetails.tsx
import { useParams, useNavigate } from 'react-router-dom';
import { useState, useEffect } from 'react';
import { Button, Spin, Timeline, Input, Form, Dropdown } from 'antd';
import { 
  ArrowLeftOutlined, 
  CalendarOutlined,
  FieldTimeOutlined,
  SendOutlined,
  SmileOutlined
} from '@ant-design/icons';
import { projectService } from '../../services/api/projectService';
import dayjs from 'dayjs';

const REACTION_TYPES = ['👍', '👎', '😄', '🎉', '😕', '❤️'];

const TaskDetails = () => {
  const { projectId, taskId } = useParams();
  const navigate = useNavigate();
  const [isLoading, setIsLoading] = useState(true);
  const [taskDetails, setTaskDetails] = useState<any>(null);
  const [newComment, setNewComment] = useState('');
  const [isLoadingComments, setIsLoadingComments] = useState(false);
  const [form] = Form.useForm();
  const [hoveredCommentId, setHoveredCommentId] = useState<string | null>(null);

  useEffect(() => {
    loadTaskDetails();
  }, [projectId, taskId]);

  const loadTaskDetails = async () => {
    if (!projectId || !taskId) return;
    
    try {
      setIsLoading(true);
      const details = await projectService.getTaskDetails(projectId, taskId);
      setTaskDetails(details);
    } catch (error) {
      console.error('Error loading task details:', error);
    } finally {
      setIsLoading(false);
    }
  };

  const getStatusClass = (status: string): string => {
    switch (status) {
      case 'Not Started':
        return 'bg-gray-500 text-gray-100';
      case 'In Progress':
        return 'bg-blue-500 text-gray-100';
      case 'Stuck':
        return 'bg-red-500 text-gray-100';
      case 'Done':
        return 'bg-green-500 text-gray-100';
      default:
        return 'bg-gray-500 text-gray-100';
    }
  };

  const getPriorityClass = (priority: string): string => {
    switch (priority.toLowerCase()) {
      case 'low':
        return 'bg-green-500 text-white';
      case 'medium':
        return 'bg-yellow-500 text-white';
      case 'high':
        return 'bg-orange-500 text-white';
      case 'critical':
        return 'bg-red-500 text-white';
      default:
        return 'bg-gray-500 text-white';
    }
  };

  const formatDate = (date: string) => {
    return dayjs(date).format('MMM D, YYYY');
  };

  const formatDateTime = (date: string) => {
    return dayjs(date).format('MMM D, YYYY h:mm A');
  };

  const handleAddComment = async () => {
    if (!newComment.trim() || !projectId || !taskId) return;

    try {
      setIsLoadingComments(true);
      const comment = await projectService.addTaskComment(projectId, taskId, {
        content: newComment.trim(),
      });
      
      setTaskDetails((prev: any) => ({
        ...prev,
        comments: [comment, ...(prev.comments || [])],
      }));
      
      setNewComment('');
      form.resetFields();
    } catch (error) {
      console.error('Error adding comment:', error);
    } finally {
      setIsLoadingComments(false);
    }
  };

  const handleReaction = async (commentId: string, type: string) => {
    if (!projectId || !taskId) return;

    try {
      // Optimistic update
      setTaskDetails((prev: any) => {
        const updatedComments = prev.comments.map((comment: any) => {
          if (comment._id !== commentId) return comment;

          const userId = localStorage.getItem('userId');
          const existingReaction = comment.reactions?.find(
            (r: any) => r.user._id === userId && r.type === type
          );

          let updatedReactions = [...(comment.reactions || [])];
          if (existingReaction) {
            updatedReactions = updatedReactions.filter(
              (r: any) => !(r.user._id === userId && r.type === type)
            );
          } else {
            updatedReactions.push({
              type,
              user: { _id: userId }
            });
          }

          return {
            ...comment,
            reactions: updatedReactions
          };
        });

        return {
          ...prev,
          comments: updatedComments
        };
      });

      // Make API call
      await projectService.addCommentReaction(projectId, taskId, commentId, type);
    } catch (error) {
      console.error('Error toggling reaction:', error);
      // Revert on error by reloading task details
      loadTaskDetails();
    }
  };

  const getReactionCount = (comment: any, type: string): number => {
    return comment.reactions?.filter((r: any) => r.type === type).length || 0;
  };

  const hasUserReacted = (comment: any, type: string): boolean => {
    const userId = localStorage.getItem('userId');
    return comment.reactions?.some((r: any) => r.user._id === userId && r.type === type) || false;
  };

  const getExistingReactionTypes = (comment: any): string[] => {
    if (!comment.reactions) return [];
    return Array.from(new Set(comment.reactions.map((r: any) => r.type)));
  };

  if (isLoading) {
    return (
      <div className="flex justify-center items-center min-h-screen">
        <Spin size="large" />
      </div>
    );
  }

  return (
    <div className="bg-gray-100 dark:bg-gray-900 min-h-screen p-4 sm:p-6 lg:p-8">
      <div className="max-w-7xl mx-auto">
        <Button
          icon={<ArrowLeftOutlined />}
          onClick={() => navigate(`/projects/${projectId}`)}
          className="mb-4 flex items-center text-gray-600 dark:text-gray-300 hover:text-gray-800 dark:hover:text-gray-100"
        >
          Back to Project
        </Button>

        {/* Two-column layout */}
        <div className="flex flex-col lg:flex-row gap-6">
          {/* Left column - Task Details */}
          <div className="lg:w-2/3 lg:flex-shrink-0">
            <div className="bg-white dark:bg-gray-800 shadow rounded-lg">
              {/* Task Header */}
              <div className="p-6 border-b border-gray-200 dark:border-gray-700">
                <div className="flex justify-between items-start mb-4">
                  <h1 className="text-2xl font-bold text-gray-900 dark:text-white">
                    {taskDetails?.title}
                  </h1>
                  <div className="flex gap-2">
                    <span className={`${getStatusClass(taskDetails?.status)} px-3 py-1 rounded-full text-sm font-semibold`}>
                      {taskDetails?.status}
                    </span>
                    <span className={`${getPriorityClass(taskDetails?.priority)} px-3 py-1 rounded-full text-sm font-semibold`}>
                      {taskDetails?.priority}
                    </span>
                    <span className="bg-gray-200 dark:bg-gray-700 text-gray-800 dark:text-gray-200 px-3 py-1 rounded-full text-sm font-semibold">
                      {taskDetails?.type}
                    </span>
                  </div>
                </div>
              </div>

              {/* Task Content */}
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6 p-6">
                {/* Timeline Info */}
                <div className="bg-blue-50 dark:bg-blue-900/50 p-4 rounded-lg">
                  <div className="flex items-center mb-2">
                    <CalendarOutlined className="text-blue-500 dark:text-blue-400 mr-2" />
                    <span className="text-sm font-medium text-gray-700 dark:text-gray-200">Start Date</span>
                  </div>
                  <p className="text-gray-900 dark:text-gray-100">
                    {taskDetails?.timeline?.start ? formatDate(taskDetails.timeline.start) : 'Not set'}
                  </p>
                </div>

                <div className="bg-green-50 dark:bg-green-900/50 p-4 rounded-lg">
                  <div className="flex items-center mb-2">
                    <CalendarOutlined className="text-green-500 dark:text-green-400 mr-2" />
                    <span className="text-sm font-medium text-gray-700 dark:text-gray-200">Due Date</span>
                  </div>
                  <p className="text-gray-900 dark:text-gray-100">
                    {taskDetails?.timeline?.end ? formatDate(taskDetails.timeline.end) : 'Not set'}
                  </p>
                </div>

                <div className="bg-purple-50 dark:bg-purple-900/50 p-4 rounded-lg">
                  <div className="flex items-center mb-2">
                    <FieldTimeOutlined className="text-purple-500 dark:text-purple-400 mr-2" />
                    <span className="text-sm font-medium text-gray-700 dark:text-gray-200">Last Updated</span>
                  </div>
                  <p className="text-gray-900 dark:text-gray-100">
                    {taskDetails?.updatedAt ? formatDate(taskDetails.updatedAt) : 'Not available'}
                  </p>
                </div>
              </div>

              {/* Description Section */}
              <div className="p-6 border-t border-gray-200 dark:border-gray-700">
                <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">Description</h2>
                <p className="text-gray-600 dark:text-gray-300">
                  {taskDetails?.description || 'No description provided'}
                </p>
              </div>

              {/* Assigned Members Section */}
              <div className="p-6 border-t border-gray-200 dark:border-gray-700">
                <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">Assigned Members</h2>
                <div className="space-y-3">
                  {taskDetails?.assignedTo?.map((member: any) => (
                    <div
                      key={member._id}
                      className="flex items-center justify-between bg-gray-50 dark:bg-gray-700/50 p-3 rounded-lg"
                    >
                      <div className="flex items-center gap-3">
                        <img
                          src={`https://ui-avatars.com/api/?name=${member.username}&background=random`}
                          alt={member.username}
                          className="w-8 h-8 rounded-full"
                        />
                        <span className="text-gray-900 dark:text-gray-100">{member.username}</span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Activity Log Section */}
              <div className="p-6 border-t border-gray-200 dark:border-gray-700">
                <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">Activity Log</h2>
                <Timeline
                  items={taskDetails?.activityLog?.map((activity: any) => ({
                    children: (
                      <div className="text-gray-600 dark:text-gray-300">
                        <p>{activity.action}</p>
                        <span className="text-sm text-gray-500 dark:text-gray-400">
                          {formatDateTime(activity.timestamp)}
                        </span>
                      </div>
                    ),
                  }))}
                />
              </div>
            </div>
          </div>

          {/* Right column - Comments */}
          <div className="lg:w-1/3">
            <div className="bg-white dark:bg-gray-800 shadow rounded-lg overflow-hidden lg:sticky lg:top-6">
              <div className="p-6">
                <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4 flex items-center">
                  <span className="mr-2">💬</span>
                  Comments
                </h2>

                {/* Comment form */}
                <Form form={form} className="mb-6">
                  <Form.Item>
                    <Input.TextArea
                      value={newComment}
                      onChange={(e) => setNewComment(e.target.value)}
                      placeholder="Write your comment here..."
                      maxLength={1000}
                      rows={3}
                      className="resize-none"
                    />
                    <div className="flex justify-between mt-1">
                      <span className="text-sm text-gray-500 dark:text-gray-400">
                        Share your thoughts about this task
                      </span>
                      <span className="text-sm text-gray-500 dark:text-gray-400">
                        {newComment.length}/1000
                      </span>
                    </div>
                  </Form.Item>
                  <Button
                    type="primary"
                    onClick={handleAddComment}
                    loading={isLoadingComments}
                    disabled={!newComment.trim()}
                    className="w-full"
                  >
                    Add Comment
                  </Button>
                </Form>

                {/* Comments list */}
                <div className="space-y-4 max-h-[calc(100vh-300px)] overflow-y-auto">
                  {(!taskDetails?.comments || taskDetails.comments.length === 0) && (
                    <div className="text-center text-gray-500 py-4">
                      <span className="text-4xl mb-2">💭</span>
                      <p>No comments yet. Be the first to comment!</p>
                    </div>
                  )}

                  {taskDetails?.comments?.map((comment: any) => (
                    <div
                      key={comment._id}
                      className="border-b border-gray-200 dark:border-gray-700 last:border-0 pb-4 hover:bg-gray-50 dark:hover:bg-gray-700/50 transition-colors duration-200 p-3 rounded-lg"
                    >
                      <div className="flex items-start space-x-3">
                        <img
                          src={`https://ui-avatars.com/api/?name=${comment.author?.username || 'User'}&background=random`}
                          alt={comment.author?.username || 'User'}
                          className="w-10 h-10 rounded-full shadow-sm"
                        />
                        <div className="flex-1 min-w-0">
                          <div className="flex justify-between items-start">
                            <div>
                              <p className="font-medium text-sm text-gray-900 dark:text-gray-100">
                                {comment.author?.username || "Unknown User"}
                              </p>
                              <p className="text-xs text-gray-500 dark:text-gray-400">
                                {formatDateTime(comment.createdAt)}
                              </p>
                            </div>
                            <div className="opacity-0 group-hover:opacity-100 transition-opacity">
                              <Dropdown
                                menu={{
                                  items: REACTION_TYPES.map(type => ({
                                    key: type,
                                    label: (
                                      <span className={hasUserReacted(comment, type) ? 'text-blue-500' : ''}>
                                        {type}
                                      </span>
                                    ),
                                    onClick: () => handleReaction(comment._id, type)
                                  }))
                                }}
                                trigger={['click']}
                              >
                                <Button
                                  type="text"
                                  icon={<SmileOutlined />}
                                  className="text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200"
                                />
                              </Dropdown>
                            </div>
                          </div>
                          <p className="mt-2 text-gray-600 dark:text-gray-300">{comment.content}</p>
                          {getExistingReactionTypes(comment).length > 0 && (
                            <div className="flex flex-wrap gap-2 mt-3">
                              {getExistingReactionTypes(comment).map((type) => (
                                <button
                                  key={type}
                                  onClick={() => handleReaction(comment._id, type)}
                                  className={`inline-flex items-center gap-1 px-2 py-1 rounded-full transition-colors ${
                                    hasUserReacted(comment, type)
                                      ? 'bg-blue-100 dark:bg-blue-900/50 text-blue-600 dark:text-blue-400'
                                      : 'bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-300'
                                  } hover:bg-gray-200 dark:hover:bg-gray-600`}
                                >
                                  <span>{type}</span>
                                  <span className="text-xs text-gray-500 dark:text-gray-400">
                                    {getReactionCount(comment, type)}
                                  </span>
                                </button>
                              ))}
                            </div>
                          )}
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TaskDetails;

// src/app/task-details/task-details.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { ProjectService } from '../services/project.service';
import { MatDialog } from '@angular/material/dialog';
import { EditTaskDialogComponent } from './edit-task-dialog/edit-task-dialog.component';
import { MatSidenavModule } from '@angular/material/sidenav';
import { CommonModule } from '@angular/common';
import { SidebarComponent } from '../shared/sidebar/sidebar.component';
import { NavbarComponent } from '../shared/navbar/navbar.component';
import { MatCardModule } from '@angular/material/card';
import { MatChipsModule } from '@angular/material/chips';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';
import { MatDialogModule } from '@angular/material/dialog';
import { provideNativeDateAdapter } from '@angular/material/core';
import { ConfirmDialogComponent } from '../shared/confirm-dialog/confirm-dialog.component';


@Component({
  selector: 'app-task-details',
  standalone: true,
  imports: [
    CommonModule,
    MatSidenavModule,
    SidebarComponent,
    NavbarComponent,
    MatCardModule,
    MatChipsModule,
    MatIconModule,
    MatButtonModule,
    MatDialogModule,
    EditTaskDialogComponent
  ],
  providers: [provideNativeDateAdapter()],
  templateUrl: './task-details.component.html',
  styleUrls: ['./task-details.component.css']
})
export class TaskDetailsComponent implements OnInit {
  task: any;
  projectId: string | null = null;
  taskId: string | null = null;
  projectMembers: any[] = [];

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private projectService: ProjectService,
    private dialog: MatDialog
  ) {}

  ngOnInit(): void {
    this.route.params.subscribe(params => {
      this.projectId = params['projectId'];
      this.taskId = params['taskId'];
      if (this.projectId && this.taskId) {
        this.loadTaskDetails();
        this.loadProjectMembers();
      }
    });
  }

  loadTaskDetails(): void {
    if (this.projectId && this.taskId) {
      this.projectService.getTaskDetails(this.projectId!, this.taskId!).subscribe(
        (task) => {
          this.task = task;
          console.log('Loaded task:', this.task); // Add this line for debugging
        },
        (error) => {
          console.error('Error loading task details:', error);
        }
      );
    }
  }

  loadProjectMembers(): void {
    if (this.projectId) {
      this.projectService.getProjectDetails(this.projectId!).subscribe(
        (project) => {
          this.projectMembers = project.members;
        },
        (error) => {
          console.error('Error loading project members:', error);
        }
      );
    }
  }

  getStatusColor(status: string): string {
    switch (status) {
      case 'Not Started': return 'gray';
      case 'In Progress': return 'blue';
      case 'Stuck': return 'red';
      case 'Done': return 'green';
      default: return 'gray';
    }
  }

  getPriorityColor(priority: string): string {
    switch (priority) {
      case 'low': return 'green';
      case 'medium': return 'orange';
      case 'high': return 'red';
      case 'critical': return 'purple';
      default: return 'gray';
    }
  }

  formatDate(date: string | Date): string {
    return new Date(date).toLocaleDateString();
  }

  deleteTask(): void {
    const dialogRef = this.dialog.open(ConfirmDialogComponent, {
      width: '250px',
      data: { title: 'Confirm Delete', message: 'Are you sure you want to delete this task?' }
    });

    dialogRef.afterClosed().subscribe(result => {
      if (result && this.projectId && this.taskId) {
        this.projectService.deleteTask(this.projectId, this.taskId).subscribe(
          () => {
            // Navigate back to the project details page or update the task list
            this.router.navigate(['/projects', this.projectId]);
          },
          error => {
            console.error('Error deleting task:', error);
            // Handle error (e.g., show an error message to the user)
          }
        );
      }
    });
  }

  editTask(): void {
    const dialogRef = this.dialog.open(EditTaskDialogComponent, {
      width: '500px',
      data: { ...this.task, projectId: this.projectId }
    });

    dialogRef.afterClosed().subscribe(result => {
      if (result) {
        this.projectService.updateTask(this.projectId!, this.taskId!, result).subscribe(
          updatedTask => {
            this.task = updatedTask;
            // Optionally, show a success message
          },
          error => {
            console.error('Error updating task:', error);
            // Handle error (e.g., show an error message to the user)
          }
        );
      }
    });
  }

  getAssignedMemberNames(): string {
    if (!this.task || !this.task.assignedTo || !Array.isArray(this.task.assignedTo)) {
      return 'No members assigned';
    }
    return this.task.assignedTo
      .filter((member: any) => member !== null && member !== undefined)
      .map((member: any) => {
        if (typeof member === 'object' && member !== null && member.username) {
          return member.username;
        } else if (typeof member === 'string') {
          const foundMember = this.projectMembers.find(m => m._id === member);
          return foundMember ? foundMember.username : 'Unknown';
        }
        return 'Unknown';
      })
      .join(', ');
  }
}

<div class="max-w-4xl mx-auto p-6" *ngIf="task">
  <div class="mb-8">
    <h1 class="text-3xl font-bold text-gray-800 mb-4">{{ task.title }}</h1>
    <div class="flex flex-wrap gap-2">
      <button 
        [matMenuTriggerFor]="statusMenu" 
        [ngClass]="getStatusClass(task.status)" 
        class="px-3 py-1 rounded-full text-sm font-medium flex items-center transition-colors duration-200 ease-in-out focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
      >
        <span class="mr-1">{{ task.status }}</span>
        <mat-icon class="text-sm">arrow_drop_down</mat-icon>
      </button>
      <mat-menu #statusMenu="matMenu" class="custom-menu">
        <button mat-menu-item (click)="updateTaskStatus('Not Started')" class="flex items-center">
          <span class="w-3 h-3 rounded-full bg-gray-500 mr-2"></span>
          Not Started
        </button>
        <button mat-menu-item (click)="updateTaskStatus('In Progress')" class="flex items-center">
          <span class="w-3 h-3 rounded-full bg-blue-500 mr-2"></span>
          In Progress
        </button>
        <button mat-menu-item (click)="updateTaskStatus('Stuck')" class="flex items-center">
          <span class="w-3 h-3 rounded-full bg-red-500 mr-2"></span>
          Stuck
        </button>
        <button mat-menu-item (click)="updateTaskStatus('Done')" class="flex items-center">
          <span class="w-3 h-3 rounded-full bg-green-500 mr-2"></span>
          Done
        </button>
      </mat-menu>
      <span [ngClass]="getPriorityClass(task.priority)" class="px-3 py-1 rounded-full text-sm font-medium">
        {{ task.priority }}
      </span>
      <span class="bg-gray-200 text-gray-800 px-3 py-1 rounded-full text-sm font-medium">
        {{ task.type }}
      </span>
    </div>
  </div>

  <div class="bg-white shadow rounded-lg overflow-hidden mb-8">
    <div class="p-6">
      <h2 class="text-xl font-semibold text-gray-800 mb-4">Description</h2>
      <p class="text-gray-600">{{ task.description }}</p>
    </div>
    <div class="border-t border-gray-200 p-6">
      <h2 class="text-xl font-semibold text-gray-800 mb-4">Timeline</h2>
      <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div class="bg-blue-50 p-4 rounded-lg">
          <div class="flex items-center mb-2">
            <mat-icon class="text-blue-500 mr-2">event</mat-icon>
            <span class="font-semibold text-blue-700">Start Date</span>
          </div>
          <p class="text-blue-800">{{ task.timeline.start | date:'dd/MM/yyyy' }}</p>
        </div>
        <div class="bg-green-50 p-4 rounded-lg">
          <div class="flex items-center mb-2">
            <mat-icon class="text-green-500 mr-2">event</mat-icon>
            <span class="font-semibold text-green-700">End Date</span>
          </div>
          <p class="text-green-800">{{ task.timeline.end | date:'dd/MM/yyyy' }}</p>
        </div>
        <div class="bg-purple-50 p-4 rounded-lg">
          <div class="flex items-center mb-2">
            <mat-icon class="text-purple-500 mr-2">timer</mat-icon>
            <span class="font-semibold text-purple-700">Remaining Time</span>
          </div>
          <p [ngClass]="{
            'text-purple-800': remainingTime !== 'Overdue',
            'text-red-600 font-bold': remainingTime === 'Overdue'
          }">
            {{ remainingTime }}
          </p>
        </div>
      </div>
    </div>
    <div class="border-t border-gray-200 p-6">
      <h2 class="text-xl font-semibold text-gray-800 mb-4">Assigned To</h2>
      <p class="text-gray-600">{{ getAssignedMemberNames() }}</p>
    </div>
  </div>

  <div class="flex justify-end space-x-4" *ngIf="isProjectCreator">
    <button mat-raised-button color="primary" (click)="editTask()" class="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded-md flex items-center">
      <mat-icon class="mr-2">edit</mat-icon>
      Edit Task
    </button>
    <button mat-raised-button color="warn" (click)="deleteTask()" class="bg-red-500 hover:bg-red-600 text-white px-4 py-2 rounded-md flex items-center">
      <mat-icon class="mr-2">delete</mat-icon>
      Delete Task
    </button>
  </div>

  <div class="bg-white shadow rounded-lg overflow-hidden mt-8">
    <div class="p-6">
      <h2 class="text-2xl font-semibold text-gray-800 mb-6">Activity Log</h2>
      <div class="flow-root">
        <ul role="list" class="-mb-8">
          <li *ngFor="let activity of activityLog; let last = last">
            <div class="relative pb-8">
              <span class="absolute top-5 left-5 -ml-px h-full w-0.5 bg-gray-200" aria-hidden="true" *ngIf="!last"></span>
              <div class="relative flex items-start space-x-3">
                <div class="relative">
                  <img class="h-10 w-10 rounded-full bg-gray-400 flex items-center justify-center ring-8 ring-white" 
                       [src]="'https://ui-avatars.com/api/?name=' + (activity.performedBy?.username || 'User') + '&background=random'" 
                       [alt]="activity.performedBy?.username || 'User'">
                </div>
                <div class="min-w-0 flex-1">
                  <div>
                    <div class="text-sm">
                      <a href="#" class="font-medium text-gray-900">{{ activity.performedBy?.username || 'Unknown User' }}</a>
                    </div>
                    <div class="mt-0.5 text-sm text-gray-500">
                      {{ activity.timestamp | date:'dd/MM/yyyy HH:mm' }}
                    </div>
                  </div>
                  <div class="mt-2 text-sm text-gray-700">
                    <p [innerHTML]="formatActivityAction(activity.action)"></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
        </ul>
      </div>
      <mat-paginator
        [length]="totalLogs"
        [pageSize]="5"
        [pageIndex]="currentPage - 1"
        (page)="onPageChange($event)"
        aria-label="Select page of activity logs">
      </mat-paginator>
    </div>
  </div>
</div>
