// frontend/src/app/shared/navbar/navbar.component.ts
import { Component, OnInit, Output, EventEmitter } from '@angular/core';
import { MatToolbarModule } from '@angular/material/toolbar';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatMenuModule } from '@angular/material/menu';
import { RouterModule, Router } from '@angular/router';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../../services/auth.service';
import { SearchService } from '../../services/search.service';
import { NotificationMenuComponent } from '../../components/notification-menu/notification-menu.component';
import { debounceTime, distinctUntilChanged, Subject } from 'rxjs';
import { ThemeService } from '../../services/theme.service';
import { Observable } from 'rxjs';

interface SearchResult {
  type: 'project' | 'task';
  _id: string;
  name?: string;
  title?: string;
  description?: string;
  projectId?: string;
  projectName?: string;
}

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  standalone: true,
  imports: [
    CommonModule,
    MatToolbarModule,
    MatButtonModule,
    MatIconModule,
    MatMenuModule,
    RouterModule,
    FormsModule,
    NotificationMenuComponent,
  ],
})
export class NavbarComponent implements OnInit {
  username: string | null = null;
  searchTerm: string = '';
  searchResults: SearchResult[] = [];
  showDropdown = false;
  private searchSubject = new Subject<string>();
  isDarkMode$: Observable<boolean>;
  showMobileSearch = false;

  @Output() toggleSidebar = new EventEmitter<void>();

  constructor(
    private authService: AuthService,
    private router: Router,
    private searchService: SearchService,
    private themeService: ThemeService
  ) {
    this.isDarkMode$ = this.themeService.darkMode$;
    this.setupSearch();
  }

  private setupSearch() {
    this.searchSubject.pipe(
      debounceTime(300),
      distinctUntilChanged()
    ).subscribe(term => {
      if (term.trim().length >= 2) {
        this.searchService.searchProjectsAndTasks(term).subscribe({
          next: (results) => {
            this.searchResults = results.slice(0, 5); // Limit to 5 results
            this.showDropdown = true;
          },
          error: (error) => console.error('Search error:', error)
        });
      } else {
        this.searchResults = [];
        this.showDropdown = false;
      }
    });
  }

  onSearchInput() {
    this.searchSubject.next(this.searchTerm);
  }

  navigateToResult(result: SearchResult) {
    if (result.type === 'project') {
      this.router.navigate(['/projects', result._id]);
    } else {
      this.router.navigate(['/projects', result.projectId], {
        queryParams: { taskId: result._id }
      });
    }
    this.closeDropdown();
  }

  closeDropdown() {
    this.showDropdown = false;
    this.searchResults = [];
    this.searchTerm = '';
  }

  ngOnInit() {
    this.updateUsername();
  }

  updateUsername() {
    this.username = localStorage.getItem('username');
  }

  get userInitial(): string {
    return this.username ? this.username[0].toUpperCase() : '?';
  }

  logout() {
    this.authService.logout();
    this.username = null;
    this.router.navigate(['/login']);
  }

  onToggleSidebar() {
    this.toggleSidebar.emit();
  }

  isLoggedIn(): boolean {
    return this.authService.isLoggedIn();
  }

  performSearch() {
    if (this.searchTerm.trim()) {
      this.router.navigate(['/search'], {
        queryParams: { term: this.searchTerm }
      });
    }
  }

  handleBlur() {
    setTimeout(() => {
      this.closeDropdown();
    }, 200);
  }

  toggleTheme() {
    this.themeService.toggleTheme();
  }

  toggleMobileSearch() {
    this.showMobileSearch = !this.showMobileSearch;
  }
}

<nav class="bg-white dark:bg-gray-800 shadow">
  <div class="mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex justify-between h-16">
      <div class="flex items-center">
        <button
          (click)="onToggleSidebar()"
          class="p-2 rounded-md text-gray-400 hover:text-gray-500 dark:hover:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500"
        >
          <mat-icon>menu</mat-icon>
        </button>
        <div class="flex-shrink-0 flex items-center ml-4">
          <img
            class="h-8 w-auto"
            src="https://res.cloudinary.com/db2tvcbza/image/upload/v1730869163/logo_sfhhhd.png"
            alt="Logo"
            crossorigin="anonymous"
          />
        </div>
      </div>
      
      <div class="flex items-center space-x-2">
        <div class="relative hidden md:block" *ngIf="isLoggedIn()">
          <input
            type="text"
            [(ngModel)]="searchTerm"
            (input)="onSearchInput()"
            (blur)="handleBlur()"
            placeholder="Search projects and tasks..."
            class="w-64 px-4 py-2 rounded-md border border-gray-300 dark:border-gray-600 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 dark:bg-gray-700 dark:text-white"
          />
          <button
            class="absolute right-2 top-1/2 transform -translate-y-1/2 text-gray-400 hover:text-gray-600"
          >
            <mat-icon>search</mat-icon>
          </button>
          
          <!-- Search Results Dropdown -->
          <div *ngIf="showDropdown && searchResults.length > 0"
               class="absolute right-0 z-50 mt-1 w-full bg-white rounded-md shadow-lg max-h-96 overflow-auto">
            <div class="py-1">
              <div *ngFor="let result of searchResults"
                   (click)="navigateToResult(result)"
                   class="px-4 py-2 hover:bg-gray-100 cursor-pointer">
                <div class="flex items-center">
                  <mat-icon class="mr-2 text-gray-400">
                    {{result.type === 'project' ? 'folder' : 'task'}}
                  </mat-icon>
                  <div>
                    <div class="text-sm font-medium text-gray-900">
                      {{result.type === 'project' ? result.name : result.title}}
                    </div>
                    <div *ngIf="result.type === 'task'" class="text-xs text-gray-500">
                      in {{result.projectName}}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        
        <button
          *ngIf="isLoggedIn()"
          (click)="toggleMobileSearch()"
          class="md:hidden h-8 w-8 flex items-center justify-center rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 dark:hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500"
        >
          <mat-icon class="text-[20px]">search</mat-icon>
        </button>
        
        <div class="h-8 w-8 flex items-center justify-center rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 dark:hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500">
          <app-notification-menu *ngIf="isLoggedIn()"></app-notification-menu>
        </div>
        
        <button
          (click)="toggleTheme()"
          class="h-8 w-8 flex items-center justify-center rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 dark:hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500"
        >
          <mat-icon class="text-[20px]" *ngIf="isDarkMode$ | async">light_mode</mat-icon>
          <mat-icon class="text-[20px]" *ngIf="!(isDarkMode$ | async)">dark_mode</mat-icon>
        </button>
        <button
          [matMenuTriggerFor]="userMenu"
          class="h-8 w-8 flex items-center justify-center rounded-full focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 overflow-hidden"
        >
          <span class="sr-only">Open user menu</span>
          <img
            class="h-full w-full object-cover"
            [src]="'https://ui-avatars.com/api/?name=' + (username || 'User') + '&background=random'"
            [alt]="username || 'User'"
          />
        </button>
      </div>
    </div>

    <div *ngIf="showMobileSearch && isLoggedIn()" class="md:hidden pb-2 px-2">
      <div class="relative">
        <input
          type="text"
          [(ngModel)]="searchTerm"
          (input)="onSearchInput()"
          (blur)="handleBlur()"
          placeholder="Search projects and tasks..."
          class="w-full px-4 py-2 rounded-md border border-gray-300 dark:border-gray-600 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 dark:bg-gray-700 dark:text-white"
        />
        <button
          class="absolute right-2 top-1/2 transform -translate-y-1/2 text-gray-400 hover:text-gray-600"
        >
          <mat-icon>search</mat-icon>
        </button>
        
        <!-- Mobile Search Results Dropdown -->
        <div *ngIf="showDropdown && searchResults.length > 0"
             class="absolute left-0 right-0 z-50 mt-1 bg-white rounded-md shadow-lg max-h-96 overflow-auto">
          <div class="py-1">
            <div *ngFor="let result of searchResults"
                 (click)="navigateToResult(result)"
                 class="px-4 py-2 hover:bg-gray-100 cursor-pointer">
              <div class="flex items-center">
                <mat-icon class="mr-2 text-gray-400">
                  {{result.type === 'project' ? 'folder' : 'task'}}
                </mat-icon>
                <div>
                  <div class="text-sm font-medium text-gray-900">
                    {{result.type === 'project' ? result.name : result.title}}
                  </div>
                  <div *ngIf="result.type === 'task'" class="text-xs text-gray-500">
                    in {{result.projectName}}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <mat-menu #userMenu="matMenu" class="mt-2">
    <div class="bg-white dark:bg-gray-800 py-1">
      <button
        mat-menu-item
        routerLink="/profile"
        class="flex items-center w-full px-4 py-2 text-sm text-gray-700 dark:text-gray-200 hover:bg-gray-100 dark:hover:bg-gray-700"
      >
        <mat-icon class="mr-3 text-gray-400 dark:text-gray-500">person</mat-icon>
        <span>Profile</span>
      </button>

      <button
        mat-menu-item
        (click)="logout()"
        class="flex items-center w-full px-4 py-2 text-sm text-gray-700 dark:text-gray-200 hover:bg-gray-100 dark:hover:bg-gray-700"
      >
        <mat-icon class="mr-3 text-gray-400 dark:text-gray-500">exit_to_app</mat-icon>
        <span>Logout</span>
      </button>
    </div>
  </mat-menu>
</nav>

// frontend-react/src/components/layout/Navbar.tsx
import { useState, useCallback, useRef, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Input, Avatar, Dropdown, Button, List } from 'antd';
import debounce from 'lodash/debounce';
import { 
  MenuOutlined, 
  SearchOutlined, 
  BellOutlined,
  UserOutlined,
  LogoutOutlined,
  SunOutlined,
  MoonOutlined,
  FolderOutlined,
  CheckSquareOutlined
} from '@ant-design/icons';
import { useTheme } from '../../context/ThemeContext';
import { searchService } from '../../services/api/searchService';
import type { SearchResult } from '../../services/api/searchService';

interface NavbarProps {
  toggleSidebar: () => void;
  isDarkMode: boolean;
}

const Navbar = ({ toggleSidebar, isDarkMode }: NavbarProps) => {
  const navigate = useNavigate();
  const { toggleTheme } = useTheme();
  const [searchTerm, setSearchTerm] = useState('');
  const [searchResults, setSearchResults] = useState<SearchResult[]>([]);
  const [showResults, setShowResults] = useState(false);
  const [isSearching, setIsSearching] = useState(false);
  const searchRef = useRef<HTMLDivElement>(null);
  const [showMobileSearch, setShowMobileSearch] = useState(false);
  const user = JSON.parse(localStorage.getItem('user') || '{}');
  const userMenuItems = [
    {
      key: 'profile',
      label: 'Profile',
      icon: <UserOutlined />,
      onClick: () => navigate('/profile')
    },
    {
      key: 'logout',
      label: 'Logout',
      icon: <LogoutOutlined />,
      onClick: () => navigate('/login')
    }
  ];

  // Close dropdown when clicking outside
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (searchRef.current && !searchRef.current.contains(event.target as Node)) {
        setShowResults(false);
      }
    };

    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  const performSearch = useCallback(
    debounce(async (term: string) => {
      if (!term.trim()) {
        setSearchResults([]);
        setShowResults(false);
        return;
      }

      try {
        setIsSearching(true);
        const results = await searchService.search(term);
        setSearchResults(results.slice(0, 5)); // Show only first 5 results
        setShowResults(true);
      } catch (error) {
        console.error('Search error:', error);
      } finally {
        setIsSearching(false);
      }
    }, 300),
    []
  );

  const handleSearchChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value;
    setSearchTerm(value);
    performSearch(value);
  };

  const handleResultClick = (result: SearchResult) => {
    setShowResults(false);
    setSearchTerm('');
    if (result.type === 'project') {
      navigate(`/projects/${result._id}`);
    } else {
      navigate(`/projects/${result.projectId}/tasks/${result._id}`);
    }
  };

  const renderSearchResults = () => (
    <div className={`
      absolute top-full left-0 w-[400px] mt-2 
      bg-white dark:bg-gray-800 
      rounded-lg shadow-lg 
      border border-gray-200 dark:border-gray-700 
      z-50 overflow-hidden
      transform origin-top
      animate-dropdown
    `}>
      <List
        loading={isSearching}
        dataSource={searchResults}
        renderItem={(result) => (
          <List.Item
            className="border-b last:border-b-0 border-gray-100 dark:border-gray-700 
                      hover:bg-gray-50 dark:hover:bg-gray-700 
                      transition-colors duration-150 cursor-pointer"
            onClick={() => handleResultClick(result)}
          >
            <div className="flex items-center gap-3 px-4 py-3 w-full">
              <div className={`
                flex-shrink-0 w-8 h-8 rounded-lg 
                ${result.type === 'project' ? 'bg-blue-100 dark:bg-blue-900' : 'bg-green-100 dark:bg-green-900'}
                flex items-center justify-center
              `}>
                {result.type === 'project' ? (
                  <FolderOutlined className="text-blue-600 dark:text-blue-400" />
                ) : (
                  <CheckSquareOutlined className="text-green-600 dark:text-green-400" />
                )}
              </div>
              <div className="flex-1 min-w-0">
                <div className="font-medium text-gray-900 dark:text-gray-100 truncate">
                  {result.type === 'project' ? result.name : result.title}
                </div>
                {result.type === 'task' && (
                  <div className="text-sm text-gray-500 dark:text-gray-400 truncate">
                    in {result.projectName}
                  </div>
                )}
              </div>
            </div>
          </List.Item>
        )}
        locale={{
          emptyText: (
            <div className="py-8 text-center">
              <SearchOutlined className="text-2xl text-gray-400 dark:text-gray-600 mb-2" />
              <div className="text-gray-500 dark:text-gray-400">
                {searchTerm ? 'No results found' : 'Type to search...'}
              </div>
            </div>
          )
        }}
      />
      {searchResults.length > 0 && (
        <div className="p-3 bg-gray-50 dark:bg-gray-750 border-t border-gray-200 dark:border-gray-700">
          <Button
            type="link"
            block
            onClick={() => {
              navigate(`/search?term=${encodeURIComponent(searchTerm)}`);
              setShowResults(false);
              setSearchTerm('');
            }}
            className="text-gray-600 dark:text-gray-300 hover:text-gray-800 dark:hover:text-gray-100"
          >
            View all results
          </Button>
        </div>
      )}
    </div>
  );

  return (
    <nav className={`shadow ${isDarkMode ? 'bg-gray-800' : 'bg-white'}`}>
      <div className="mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex justify-between h-16">
          <div className="flex items-center">
            <Button
              type="text"
              icon={<MenuOutlined />}
              onClick={toggleSidebar}
              className={`p-2 rounded-md ${
                isDarkMode 
                  ? 'text-gray-400 hover:text-gray-300 hover:bg-gray-700' 
                  : 'text-gray-500 hover:text-gray-700 hover:bg-gray-100'
              }`}
            />
            <div className="flex-shrink-0 flex items-center ml-4">
              <img
                className="h-8 w-auto"
                src="https://res.cloudinary.com/db2tvcbza/image/upload/v1730869163/logo_sfhhhd.png"
                alt="Logo"
                crossOrigin="anonymous"
              />
            </div>
          </div>

          <div className="flex items-center space-x-4">
            <div className="relative hidden md:block" ref={searchRef}>
              <Input
                prefix={<SearchOutlined className={isDarkMode ? 'text-gray-400' : 'text-gray-500'} />}
                placeholder="Search projects and tasks..."
                value={searchTerm}
                onChange={handleSearchChange}
                className={`w-64 transition-all duration-300 ${
                  isDarkMode ? 'bg-gray-700 border-gray-600 text-white' : ''
                }`}
              />
              {showResults && renderSearchResults()}
            </div>

            <Button
              type="text"
              icon={<SearchOutlined />}
              className={`md:hidden ${isDarkMode ? 'text-gray-400' : 'text-gray-500'}`}
              onClick={() => setShowMobileSearch(!showMobileSearch)}
            />

            <Button
              type="text"
              icon={<BellOutlined />}
              className={isDarkMode ? 'text-gray-400' : 'text-gray-500'}
            />

            <Button
              type="text"
              icon={isDarkMode ? <SunOutlined /> : <MoonOutlined />}
              onClick={toggleTheme}
              className={isDarkMode ? 'text-gray-400' : 'text-gray-500'}
            />

            <Dropdown menu={{ items: userMenuItems }} placement="bottomRight">
              <Avatar
                src={`https://ui-avatars.com/api/?name=${user?.username}&background=random`}
                className="cursor-pointer"
              />
            </Dropdown>
          </div>
        </div>

        {showMobileSearch && (
          <div className="md:hidden pb-2 px-2">
            <Input
              prefix={<SearchOutlined className={isDarkMode ? 'text-gray-400' : 'text-gray-500'} />}
              placeholder="Search projects and tasks..."
              value={searchTerm}
              onChange={handleSearchChange}
              className={`w-full ${isDarkMode ? 'bg-gray-700 border-gray-600 text-white' : ''}`}
            />
          </div>
        )}
      </div>
    </nav>
  );
};

export default Navbar;
