// frontend-react/src/pages/profile/Profile.tsx
import { useState, useEffect } from 'react';
import { Form, Input, DatePicker, Button, message, Card, Spin, Avatar } from 'antd';
import { UserOutlined, MailOutlined, LinkOutlined } from '@ant-design/icons';
import moment from 'moment';
import { userService, type UserProfile } from '../../services/api/userService';

const Profile = () => {
  const [form] = Form.useForm();
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);
  const [profile, setProfile] = useState<UserProfile | null>(null);

  useEffect(() => {
    loadUserProfile();
  }, []);

  const loadUserProfile = async () => {
    try {
      setIsLoading(true);
      const userData = await userService.getCurrentUserProfile();
      setProfile(userData);
      
      // Set form values
      form.setFieldsValue({
        username: userData.username,
        name: userData.name,
        email: userData.email,
        birthDate: userData.birthDate ? moment(userData.birthDate) : null,
        twitter: userData.socialMedia?.twitter,
        instagram: userData.socialMedia?.instagram,
        linkedin: userData.socialMedia?.linkedin,
        github: userData.socialMedia?.github
      });
    } catch (error) {
      message.error('Failed to load profile');
    } finally {
      setIsLoading(false);
    }
  };

  const onFinish = async (values: any) => {
    try {
      setIsSaving(true);
      await userService.updateUserProfile({
        name: values.name,
        email: values.email,
        birthDate: values.birthDate?.toDate(),
        socialMedia: {
          twitter: values.twitter,
          instagram: values.instagram,
          linkedin: values.linkedin,
          github: values.github
        }
      });
      message.success('Profile updated successfully');
      await loadUserProfile();
    } catch (error) {
      message.error('Failed to update profile');
    } finally {
      setIsSaving(false);
    }
  };

  if (isLoading) {
    return (
      <div className="flex justify-center items-center min-h-screen">
        <Spin size="large" />
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-100 dark:bg-gray-900 p-4 sm:p-6">
      <div className="max-w-3xl mx-auto">
        <Card className="bg-white dark:bg-gray-800 shadow-sm">
          {/* Profile Header - Similar to Angular template */}
          <div className="flex items-center space-x-5 mb-6 pb-6 border-b border-gray-200 dark:border-gray-700">
            <Avatar
              size={80}
              src={`https://ui-avatars.com/api/?name=${profile?.username}&background=random&size=80`}
              className="ring-4 ring-white dark:ring-gray-700"
            />
            <div>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-gray-100">
                {profile?.name || profile?.username}
              </h2>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                @{profile?.username}
              </p>
            </div>
          </div>

          <Form
            form={form}
            layout="vertical"
            onFinish={onFinish}
            className="space-y-4"
          >
            {/* Form fields matching the Angular template structure */}
            <div className="space-y-6">
              <h3 className="text-lg font-medium text-gray-900 dark:text-gray-100">
                Basic Information
              </h3>
              
              <Form.Item
                label="Username"
                name="username"
              >
                <Input 
                  prefix={<UserOutlined />}
                  disabled 
                  className="bg-gray-50 dark:bg-gray-700"
                />
              </Form.Item>

              <Form.Item
                label="Full Name"
                name="name"
                rules={[{ required: true, message: 'Please input your name' }]}
              >
                <Input prefix={<UserOutlined />} />
              </Form.Item>

              <Form.Item
                label="Email Address"
                name="email"
                rules={[
                  { required: true, message: 'Please input your email' },
                  { type: 'email', message: 'Please enter a valid email' }
                ]}
              >
                <Input prefix={<MailOutlined />} />
              </Form.Item>

              <Form.Item
                label="Birth Date"
                name="birthDate"
              >
                <DatePicker className="w-full" />
              </Form.Item>
            </div>

            <div className="border-t dark:border-gray-700 pt-6 mt-6">
              <h3 className="text-lg font-medium text-gray-900 dark:text-gray-100 mb-4">
                Social Media Links
              </h3>
              <div className="space-y-4">
                <Form.Item label="Twitter" name="twitter">
                  <Input prefix={<LinkOutlined />} />
                </Form.Item>

                <Form.Item label="Instagram" name="instagram">
                  <Input prefix={<LinkOutlined />} />
                </Form.Item>

                <Form.Item label="LinkedIn" name="linkedin">
                  <Input prefix={<LinkOutlined />} />
                </Form.Item>

                <Form.Item label="GitHub" name="github">
                  <Input prefix={<LinkOutlined />} />
                </Form.Item>
              </div>
            </div>

            <div className="flex justify-end pt-6 border-t dark:border-gray-700">
              <Button
                type="primary"
                htmlType="submit"
                loading={isSaving}
                className="bg-blue-500 hover:bg-blue-600"
              >
                Save Changes
              </Button>
            </div>
          </Form>
        </Card>
      </div>
    </div>
  );
};

export default Profile;

// frontend/src/app/pages/profile/profile.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatDatepickerModule } from '@angular/material/datepicker';
import { MatNativeDateModule } from '@angular/material/core';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { MatSelectModule } from '@angular/material/select';

import { UserService } from '../../services/user.service';
import { UserProfile } from '../../interfaces/user.interface';

@Component({
  selector: 'app-profile',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    RouterModule,
    MatButtonModule,
    MatIconModule,
    MatInputModule,
    MatFormFieldModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatProgressSpinnerModule,
    MatSnackBarModule,
    MatSelectModule
  ],
  templateUrl: './profile.component.html',
  styleUrls: ['./profile.component.css']
})
export class ProfileComponent implements OnInit {
  username: string = '';
  email: string = '';
  name: string = '';
  birthDate: Date | null = null;
  isLoading: boolean = false;
  isLoadingProfile: boolean = true;
  isSaving: boolean = false;
  socialMedia: {
    twitter?: string;
    instagram?: string;
    linkedin?: string;
    github?: string;
  } = {
    twitter: '',
    instagram: '',
    linkedin: '',
    github: ''
  };

  constructor(
    private userService: UserService,
    private snackBar: MatSnackBar
  ) {}

  ngOnInit(): void {
    this.loadUserProfile();
  }

  loadUserProfile(): void {
    this.isLoadingProfile = true;
    
    this.userService.getCurrentUserProfile().subscribe({
      next: (profile) => {
        this.username = profile.username;
        this.email = profile.email;
        this.name = profile.name || '';
        
        this.birthDate = profile.birthDate ? new Date(profile.birthDate) : null;

        this.socialMedia = profile.socialMedia || {
          twitter: '',
          instagram: '',
          linkedin: '',
          github: ''
        };
        this.isLoadingProfile = false;
      },
      error: (error) => {
        console.error('Error loading profile:', error);
        this.snackBar.open('Error loading profile', 'Close', { duration: 3000 });
        this.isLoadingProfile = false;
      }
    });
  }

  onSubmit(): void {
    this.isSaving = true;
    
    const updateData: Partial<UserProfile> = {
      email: this.email,
      name: this.name || undefined,
      birthDate: this.birthDate || undefined,
      socialMedia: {
        twitter: this.socialMedia.twitter || undefined,
        instagram: this.socialMedia.instagram || undefined,
        linkedin: this.socialMedia.linkedin || undefined,
        github: this.socialMedia.github || undefined
      }
    };

    this.userService.updateUserProfile(updateData).subscribe({
      next: (profile) => {
        this.snackBar.open('Profile updated successfully', 'Close', { duration: 3000 });
        this.isSaving = false;
        this.loadUserProfile();
      },
      error: (error) => {
        console.error('Error updating profile:', error);
        this.snackBar.open(error.error.message || 'Error updating profile', 'Close', { duration: 3000 });
        this.isSaving = false;
      }
    });
  }
}

<div class="bg-gray-100 min-h-screen p-4 sm:p-6 lg:p-8">
  <div *ngIf="isLoadingProfile" class="flex justify-center items-center min-h-[calc(100vh-64px)]">
    <mat-spinner diameter="40"></mat-spinner>
  </div>
  <div *ngIf="!isLoadingProfile" class="container mx-auto px-4 py-8">
    <div class="max-w-7xl mx-auto">
      <button
      mat-button
      routerLink="/dashboard"
      class="mb-4 flex items-center text-gray-600 hover:text-gray-800"
    >
      <mat-icon class="mr-2">arrow_back</mat-icon> Back to Dashboard
    </button>

    <div class="bg-white shadow rounded-lg">
      <!-- Profile Header -->
      <div class="px-4 py-5 sm:px-6 border-b border-gray-200">
        <div class="flex items-center space-x-5">
          <div class="flex-shrink-0">
            <img 
              class="h-20 w-20 rounded-full ring-4 ring-white"
              [src]="'https://ui-avatars.com/api/?name=' + (username) + '&background=random&size=80'"
              [alt]="username"
            >
          </div>
          <div class="flex-1 min-w-0">
            <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:truncate">{{ name || username }}</h2>
            <p class="text-sm text-gray-500">{{ '@' + username }}</p>
          </div>
        </div>
      </div>

      <!-- Profile Form -->
      <form (ngSubmit)="onSubmit()" #profileForm="ngForm" class="divide-y divide-gray-200">
        <!-- Basic Information -->
        <div class="px-4 py-5 sm:p-6">
          <div class="space-y-6">
            <h3 class="text-lg font-medium leading-6 text-gray-900">Basic Information</h3>
            
            <!-- Username (Read-only) -->
            <mat-form-field appearance="fill" class="w-full">
              <mat-label>Username</mat-label>
              <input matInput [value]="username" readonly>
              <mat-icon matSuffix>person</mat-icon>
              <mat-hint>Username cannot be changed</mat-hint>
            </mat-form-field>

            <!-- Name -->
            <mat-form-field appearance="fill" class="w-full">
              <mat-label>Full Name</mat-label>
              <input matInput [(ngModel)]="name" name="name" placeholder="Your full name">
              <mat-icon matSuffix>badge</mat-icon>
            </mat-form-field>

            <!-- Email -->
            <mat-form-field appearance="fill" class="w-full">
              <mat-label>Email Address</mat-label>
              <input matInput [(ngModel)]="email" name="email" type="email" placeholder="your.email@example.com">
              <mat-icon matSuffix>email</mat-icon>
            </mat-form-field>

            <!-- Birth Date -->
            <mat-form-field appearance="fill" class="w-full">
              <mat-label>Birth Date</mat-label>
              <input matInput [matDatepicker]="picker" [(ngModel)]="birthDate" name="birthDate">
              <mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
              <mat-datepicker #picker></mat-datepicker>
            </mat-form-field>
          </div>
        </div>

        <!-- Social Media Links -->
        <div class="px-4 py-5 sm:p-6">
          <div class="space-y-6">
            <h3 class="text-lg font-medium leading-6 text-gray-900">Social Media Links</h3>
            <div class="grid grid-cols-1 gap-6 sm:grid-cols-2">
              <!-- Twitter -->
              <mat-form-field appearance="fill" class="w-full">
                <mat-label>Twitter</mat-label>
                <input matInput [(ngModel)]="socialMedia.twitter" name="twitter" placeholder="Twitter profile URL">
                <mat-icon matSuffix>link</mat-icon>
              </mat-form-field>

              <!-- Instagram -->
              <mat-form-field appearance="fill" class="w-full">
                <mat-label>Instagram</mat-label>
                <input matInput [(ngModel)]="socialMedia.instagram" name="instagram" placeholder="Instagram profile URL">
                <mat-icon matSuffix>link</mat-icon>
              </mat-form-field>

              <!-- LinkedIn -->
              <mat-form-field appearance="fill" class="w-full">
                <mat-label>LinkedIn</mat-label>
                <input matInput [(ngModel)]="socialMedia.linkedin" name="linkedin" placeholder="LinkedIn profile URL">
                <mat-icon matSuffix>link</mat-icon>
              </mat-form-field>

              <!-- GitHub -->
              <mat-form-field appearance="fill" class="w-full">
                <mat-label>GitHub</mat-label>
                <input matInput [(ngModel)]="socialMedia.github" name="github" placeholder="GitHub profile URL">
                <mat-icon matSuffix>link</mat-icon>
              </mat-form-field>
            </div>
          </div>
        </div>

        <!-- Save Button -->
        <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
          <button 
            mat-raised-button
            color="primary"
            type="submit"
            [disabled]="isLoading"
            class="inline-flex items-center"
          >
            <mat-icon *ngIf="!isLoading">save</mat-icon>
            <mat-spinner
              *ngIf="isLoading"
              diameter="20"
              class="mr-2"
            ></mat-spinner>
            {{ isLoading ? 'Saving...' : 'Save Changes' }}
          </button>
        </div>
      </form>
    </div>
  </div>
</div>
