// frontend/src/app/pages/project-details/kanban-board/kanban-board.component.ts
import { Component, Input, Output, EventEmitter, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  DragDropModule,
  CdkDragDrop,
  moveItemInArray,
  transferArrayItem,
} from '@angular/cdk/drag-drop';
import { MatCardModule } from '@angular/material/card';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { Router } from '@angular/router';
import { ProjectService } from '../../../services/project.service';

interface Task {
  _id: string;
  title: string;
  description: string;
  status: string;
  priority: string;
}

interface Column {
  id: string;
  title: string;
  tasks: Task[];
}

@Component({
  selector: 'app-kanban-board',
  standalone: true,
  imports: [CommonModule, DragDropModule, MatCardModule, MatSnackBarModule],
  templateUrl: './kanban-board.component.html',
  styleUrls: ['./kanban-board.component.css'],
})
export class KanbanBoardComponent implements OnInit {
  private _tasks: Task[] = [];

  @Input() set tasks(value: Task[]) {
    this._tasks = value;
    this.distributeTasksToColumns();
  }

  get tasks(): Task[] {
    return this._tasks;
  }

  @Input() projectId!: string;
  @Input() isProjectCreator: boolean = false;
  @Output() taskMoved = new EventEmitter<{ task: Task; newStatus: string }>();
  @Output() taskClicked = new EventEmitter<Task>();

  columns: Column[] = [
    { id: 'not-started', title: 'Not Started', tasks: [] },
    { id: 'in-progress', title: 'In Progress', tasks: [] },
    { id: 'stuck', title: 'Stuck', tasks: [] },
    { id: 'done', title: 'Done', tasks: [] },
  ];

  constructor(
    private router: Router,
    private projectService: ProjectService,
    private snackBar: MatSnackBar
  ) {}

  ngOnInit() {
    this.distributeTasksToColumns();
  }

  public distributeTasksToColumns() {
    this.columns.forEach((column) => (column.tasks = []));
    this.tasks.forEach((task) => {
      const column = this.columns.find(
        (col) => col.title.toLowerCase() === task.status.toLowerCase()
      );
      if (column) {
        column.tasks.push(task);
      }
    });
  }

  drop(event: CdkDragDrop<Task[]>) {
    if (!this.isProjectCreator) {
      this.snackBar.open('Only project creator can move tasks', 'Close', {
        duration: 3000,
        panelClass: ['error-snackbar'],
        horizontalPosition: 'center',
        verticalPosition: 'bottom'
      });
      return;
    }

    if (event.previousContainer === event.container) {
      moveItemInArray(
        event.container.data,
        event.previousIndex,
        event.currentIndex
      );
    } else {
      const task = event.previousContainer.data[event.previousIndex];
      const newStatus = this.getStatusFromColumnId(event.container.id);
      
      if (task.status !== newStatus) {
        transferArrayItem(
          event.previousContainer.data,
          event.container.data,
          event.previousIndex,
          event.currentIndex
        );
        
        this.taskMoved.emit({ task, newStatus });
      }
    }
  }

  getStatusFromColumnId(columnId: string): string {
    const column = this.columns.find((col) => col.id === columnId);
    return column ? column.title : '';
  }

  onTaskClick(task: any) {
    this.taskClicked.emit(task);
  }

  getConnectedList(): string[] {
    return this.columns.map((column) => column.id);
  }

  getColumnClass(columnId: string): string {
    switch (columnId) {
      case 'not-started':
        return 'bg-gray-50 border-t-4 border-gray-300';
      case 'in-progress':
        return 'bg-blue-50 border-t-4 border-blue-400';
      case 'stuck':
        return 'bg-red-50 border-t-4 border-red-400';
      case 'done':
        return 'bg-green-50 border-t-4 border-green-400';
      default:
        return 'bg-gray-50';
    }
  }

  getTaskBorderClass(priority: string): string {
    switch (priority.toLowerCase()) {
      case 'critical':
        return 'border-purple-500';
      case 'high':
        return 'border-red-500';
      case 'medium':
        return 'border-yellow-500';
      case 'low':
        return 'border-green-500';
      default:
        return 'border-gray-300';
    }
  }

  getTaskPriorityClass(priority: string): string {
    switch (priority.toLowerCase()) {
      case 'critical':
        return 'bg-purple-600 text-white';
      case 'high':
        return 'bg-red-100 text-red-800';
      case 'medium':
        return 'bg-yellow-100 text-yellow-800';
      case 'low':
        return 'bg-green-100 text-green-800';
      default:
        return 'bg-gray-100 text-gray-800';
    }
  }
}

<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
  <div
    *ngFor="let column of columns"
    class="p-4 rounded-lg shadow"
    [ngClass]="getColumnClass(column.id)"
    cdkDropList
    [cdkDropListData]="column.tasks"
    (cdkDropListDropped)="drop($event)"
    [id]="column.id"
    [cdkDropListConnectedTo]="getConnectedList()"
  >
    <h3 class="text-lg font-semibold mb-4 text-gray-700 dark:text-gray-200">{{ column.title }}</h3>
    <div
      *ngFor="let task of column.tasks"
      cdkDrag
      (click)="onTaskClick(task)"
      class="bg-white dark:bg-gray-800 p-4 rounded shadow-sm mb-3 cursor-pointer hover:shadow-md transition-shadow duration-200 border-l-4"
      [ngClass]="getTaskBorderClass(task.priority)"
    >
      <h4 class="font-medium mb-2 text-gray-800 dark:text-gray-100">{{ task.title }}</h4>
      <p class="text-sm text-gray-600 dark:text-gray-300 mb-2 task-description" [title]="task.description">
        {{ task.description }}
      </p>
      <div class="flex justify-end items-center text-xs">
        <span class="px-2 py-1 rounded font-medium" [ngClass]="getTaskPriorityClass(task.priority)">
          {{ task.priority }}
        </span>
      </div>
    </div>
  </div>
</div>

// frontend-react/src/components/KanbanBoard/KanbanBoard.tsx
import { DragDropContext, Droppable, Draggable } from "@hello-pangea/dnd";
import { Card, Button } from "antd";
import { PlusOutlined } from "@ant-design/icons";
import { Task } from "../../types/project.types";

interface KanbanBoardProps {
  tasks: Task[];
  onTaskMove: (task: Task, newStatus: 'Not Started' | 'In Progress' | 'Stuck' | 'Done') => Promise<void>;
  onAddTask: () => void;
  onTaskClick: (task: Task) => void;
  isProjectCreator: boolean;
}

const STATUSES = [
  { id: 'Not Started', color: 'bg-gray-50 dark:bg-gray-900 border-t-4 border-gray-300 dark:border-gray-600' },
  { id: 'In Progress', color: 'bg-blue-50 dark:bg-blue-900/30 border-t-4 border-blue-400 dark:border-blue-500' },
  { id: 'Stuck', color: 'bg-red-50 dark:bg-red-900/30 border-t-4 border-red-400 dark:border-red-500' },
  { id: 'Done', color: 'bg-green-50 dark:bg-green-900/30 border-t-4 border-green-400 dark:border-green-500' }
];

const KanbanBoard = ({
  tasks,
  onTaskMove,
  onAddTask,
  onTaskClick,
  isProjectCreator,
}: KanbanBoardProps) => {
  const getTasksByStatus = (status: string) => {
    return tasks.filter((task) => task.status === status);
  };

  const getPriorityColor = (priority: string) => {
    switch (priority.toLowerCase()) {
      case "critical":
        return "bg-purple-600 text-white dark:bg-purple-700";
      case "high":
        return "bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-100";
      case "medium":
        return "bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-100";
      case "low":
        return "bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-100";
      default:
        return "bg-gray-100 text-gray-800 dark:bg-gray-900 dark:text-gray-100";
    }
  };
 

  const onDragEnd = async (result: any) => {
    const { destination, source, draggableId } = result;

    if (!destination || !isProjectCreator) {
      return;
    }

    if (
      destination.droppableId === source.droppableId &&
      destination.index === source.index
    ) {
      return;
    }

    const task = tasks.find((t) => t._id === draggableId);
    if (task && destination.droppableId !== task.status) {
      try {
        if (onDragEnd.isMoving) return;
        onDragEnd.isMoving = true;
        
        await onTaskMove(task, destination.droppableId);
      } catch (error) {
        console.error('Error in onDragEnd:', error);
      } finally {
        onDragEnd.isMoving = false;
      }
    }
  };

  onDragEnd.isMoving = false;

  return (
    <div className="mb-8">
      <div className="flex justify-between items-center mb-6">
        <h3 className="text-xl font-semibold dark:text-gray-200">Tasks</h3>
        {isProjectCreator && (
          <Button
            type="primary"
            icon={<PlusOutlined />}
            onClick={onAddTask}
            className="bg-blue-600"
          >
            Add Task
          </Button>
        )}
      </div>

      <DragDropContext onDragEnd={onDragEnd}>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          {STATUSES.map((status) => (
            <div key={status.id} className={`p-4 rounded-lg shadow ${status.color}`}>
              <h4 className="text-lg font-semibold mb-4 text-gray-700 dark:text-gray-200">
                {status.id} ({getTasksByStatus(status.id).length})
              </h4>
              <Droppable droppableId={status.id}>
                {(provided) => (
                  <div
                    ref={provided.innerRef}
                    {...provided.droppableProps}
                    className={`flex-1 p-4 rounded-lg min-h-[200px] `}
                  >
                    {getTasksByStatus(status.id).map((task, index) => (
                      <Draggable
                        key={task._id}
                        draggableId={task._id}
                        index={index}
                        isDragDisabled={!isProjectCreator}
                      >
                        {(provided, snapshot) => (
                          <div
                            ref={provided.innerRef}
                            {...provided.draggableProps}
                            {...provided.dragHandleProps}
                          >
                            <Card
                              className={`mb-4 cursor-pointer ${
                                snapshot.isDragging ? "shadow-lg" : ""
                              } dark:bg-gray-700`}
                              onClick={() => onTaskClick(task)}
                            >
                              <div className="space-y-2">
                                <h5 className="font-medium dark:text-gray-200">
                                  {task.title}
                                </h5>
                                <p className="text-sm text-gray-600 dark:text-gray-400 line-clamp-2">
                                  {task.description}
                                </p>
                                <div className="flex items-center justify-between">
                                  <span
                                    className={`px-2 py-1 rounded-full text-xs font-medium ${getPriorityColor(
                                      task.priority
                                    )}`}
                                  >
                                    {task.priority}
                                  </span>
                                </div>
                              </div>
                            </Card>
                          </div>
                        )}
                      </Draggable>
                    ))}
                    {provided.placeholder}
                  </div>
                )}
              </Droppable>
            </div>
          ))}
        </div>
      </DragDropContext>
    </div>
  );
};

export default KanbanBoard;
