// frontend/src/app/pages/search/search.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatInputModule } from '@angular/material/input';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatSelectModule } from '@angular/material/select';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { SearchService } from '../../services/search.service';
import { Router } from '@angular/router';
import { FormControl, FormGroup } from '@angular/forms';
import { debounceTime, distinctUntilChanged, switchMap, finalize } from 'rxjs/operators';
import { Subject, Subscription, of } from 'rxjs';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { trigger, state, style, transition, animate } from '@angular/animations';

@Component({
  selector: 'app-search',
  standalone: true,
  imports: [
    CommonModule,
    MatInputModule,
    MatFormFieldModule,
    MatSelectModule,
    FormsModule,
    ReactiveFormsModule,
    MatButtonModule,
    MatIconModule,
    MatProgressSpinnerModule
  ],
  templateUrl: './search.component.html',
  styleUrls: ['./search.component.css'],
  animations: [
    trigger('slideInOut', [
      transition(':enter', [
        style({ opacity: 0, height: 0 }),
        animate('200ms ease-out', style({ opacity: 1, height: '*' }))
      ]),
      transition(':leave', [
        animate('200ms ease-in', style({ opacity: 0, height: 0 }))
      ])
    ])
  ]
})
export class SearchComponent implements OnInit, OnDestroy {
  searchForm = new FormGroup({
    searchTerm: new FormControl(''),
    status: new FormControl(''),
    priority: new FormControl(''),
    type: new FormControl(''),
  });

  searchResults: any[] = [];
  private searchSubscription: Subscription | null = null;
  private unsubscribe$ = new Subject<void>();

  statusOptions = ['Not Started', 'In Progress', 'Stuck', 'Done'];
  priorityOptions = ['none', 'low', 'medium', 'high', 'critical'];
  typeOptions = ['task', 'bug'];

  isFiltersVisible = false;
  isLoading: boolean = false;

  constructor(private searchService: SearchService, private router: Router) { }

  ngOnInit() {
    this.searchSubscription = this.searchForm.valueChanges
      .pipe(
        debounceTime(300),
        distinctUntilChanged(),
        switchMap((formValue) => {
          if (formValue.searchTerm && formValue.searchTerm.trim() !== '') {
            return this.searchService.searchProjectsAndTasks(
              formValue.searchTerm,
              formValue.status || undefined,
              formValue.priority || undefined,
              formValue.type || undefined
            );
          } else {
            return of([]);
          }
        })
      )
      .subscribe({
        next: (results) => {
          this.searchResults = results;
        },
        error: (error) => {
          console.error('Error searching:', error);
        },
      });
  }

  ngOnDestroy() {
    if (this.searchSubscription) {
      this.searchSubscription.unsubscribe();
    }
    this.unsubscribe$.next();
    this.unsubscribe$.complete();
  }

  navigateToProject(projectId: string) {
    this.router.navigate(['/projects', projectId]);
  }

  navigateToTask(projectId: string, taskId: string) {
    this.router.navigate(['/projects', projectId, 'tasks', taskId]);
  }

  toggleFilters() {
    this.isFiltersVisible = !this.isFiltersVisible;
  }
}

<div class="bg-gradient-to-br from-gray-50 to-gray-100 min-h-screen p-4 sm:p-6 lg:p-8">
  <div class="max-w-7xl mx-auto">
    <!-- Search Container -->
    <div class="bg-white backdrop-blur-lg rounded-2xl p-8 shadow-lg border border-gray-100">
      <h2 class="text-3xl font-bold text-gray-800 mb-2 text-center">Search</h2>
      <p class="text-gray-500 text-center mb-8">Find projects and tasks across your workspace</p>
      
      <!-- Search Form -->
      <form [formGroup]="searchForm" class="space-y-6">
        <!-- Centered Search Row with Filter Toggle -->
        <div class="flex justify-center items-center max-w-2xl mx-auto relative">
          <mat-form-field appearance="fill" class="w-full">
            <mat-label>Search projects & tasks</mat-label>
            <input matInput 
                   formControlName="searchTerm" 
                   placeholder="Type to search...">
            <mat-icon matSuffix>search</mat-icon>
          </mat-form-field>

          <button mat-icon-button
                  type="button"
                  [color]="isFiltersVisible ? 'primary' : ''"
                  (click)="toggleFilters()"
                  class="ml-2 filter-toggle-btn">
            <mat-icon>filter_list</mat-icon>
          </button>
        </div>

        <!-- Filters Section -->
        <div class="bg-gray-50 rounded-xl p-6" 
             [@slideInOut]="isFiltersVisible"
             *ngIf="isFiltersVisible">
          <div class="flex space-x-4">
            <!-- Status Filter -->
            <mat-form-field appearance="fill" class="w-1/3">
              <mat-label>Status</mat-label>
              <mat-select formControlName="status">
                <mat-option value="">All Statuses</mat-option>
                <mat-option *ngFor="let status of statusOptions" [value]="status">
                  <div class="flex items-center">
                    <span class="w-2 h-2 rounded-full mr-2"
                          [ngClass]="{
                            'bg-gray-400': status === 'Not Started',
                            'bg-blue-400': status === 'In Progress',
                            'bg-red-400': status === 'Stuck',
                            'bg-green-400': status === 'Done'
                          }"></span>
                    {{status}}
                  </div>
                </mat-option>
              </mat-select>
              <mat-icon matSuffix>flag</mat-icon>
            </mat-form-field>

            <!-- Type Filter -->
            <mat-form-field appearance="fill" class="w-1/3">
              <mat-label>Type</mat-label>
              <mat-select formControlName="type">
                <mat-option value="">All Types</mat-option>
                <mat-option *ngFor="let type of typeOptions" [value]="type">
                  <div class="flex items-center">
                    <mat-icon class="mr-2">{{type === 'task' ? 'task_alt' : 'bug_report'}}</mat-icon>
                    {{type | titlecase}}
                  </div>
                </mat-option>
              </mat-select>
              <mat-icon matSuffix>category</mat-icon>
            </mat-form-field>

            <!-- Priority Filter -->
            <mat-form-field appearance="fill" class="w-1/3">
              <mat-label>Priority</mat-label>
              <mat-select formControlName="priority">
                <mat-option value="">All Priorities</mat-option>
                <mat-option *ngFor="let priority of priorityOptions" [value]="priority">
                  <div class="flex items-center">
                    <mat-icon class="mr-2 text-sm" [ngClass]="{
                      'text-gray-400': priority === 'none',
                      'text-green-400': priority === 'low',
                      'text-yellow-400': priority === 'medium',
                      'text-orange-400': priority === 'high',
                      'text-red-400': priority === 'critical'
                    }">{{ priority === 'none' ? 'remove' : 'priority_high' }}</mat-icon>
                    {{priority | titlecase}}
                  </div>
                </mat-option>
              </mat-select>
              <mat-icon matSuffix>priority_high</mat-icon>
            </mat-form-field>
          </div>
        </div>
      </form>

      <!-- Results Section -->
      <div class="mt-8 space-y-4">
        <!-- Results Header -->
        <div *ngIf="searchResults.length > 0" class="flex items-center justify-between mb-6">
          <h3 class="text-lg font-medium text-gray-700">
            Results ({{searchResults.length}})
          </h3>
          <div class="text-sm text-gray-500">
            Showing all matches
          </div>
        </div>

        <!-- Results Cards -->
        <div class="space-y-4">
          <div *ngFor="let result of searchResults" 
               class="bg-white border rounded-lg p-4 hover:shadow-md transition-all duration-200">
            <div class="flex justify-between items-start">
              <div class="flex-1">
                <div class="flex items-center mb-2">
                  <mat-icon class="mr-2 text-gray-400">
                    {{result.type === 'task' ? 'task_alt' : 'folder'}}
                  </mat-icon>
                  <h3 class="text-lg font-semibold text-gray-800">
                    {{result.type === 'task' || result.type === 'bug' ? result.title : result.name}}
                  </h3>
                </div>
                <p class="text-gray-600 mb-3">{{result.description}}</p>
                
                <div class="flex gap-2">
                  <span *ngIf="result.status" 
                        class="px-2 py-1 text-sm rounded-full"
                        [ngClass]="{
                          'bg-gray-100 text-gray-600': result.status === 'Not Started',
                          'bg-blue-100 text-blue-600': result.status === 'In Progress',
                          'bg-red-100 text-red-600': result.status === 'Stuck',
                          'bg-green-100 text-green-600': result.status === 'Done'
                        }">
                    {{result.status}}
                  </span>
                  <span *ngIf="result.priority" 
                        class="px-2 py-1 text-sm rounded-full"
                        [ngClass]="{
                          'bg-gray-100 text-gray-600': result.priority === 'none',
                          'bg-green-100 text-green-600': result.priority === 'low',
                          'bg-yellow-100 text-yellow-600': result.priority === 'medium',
                          'bg-orange-100 text-orange-600': result.priority === 'high',
                          'bg-red-100 text-red-600': result.priority === 'critical'
                        }">
                    {{result.priority | titlecase}}
                  </span>
                  <span class="px-2 py-1 text-sm rounded-full bg-gray-100 text-gray-600">
                    {{result.type | titlecase}}
                  </span>
                </div>
              </div>
              
              <button mat-flat-button color="primary" 
                      class="ml-4"
                      (click)="result.type === 'project' ? navigateToProject(result._id) : navigateToTask(result.projectId, result._id)">
                <mat-icon class="mr-2">{{result.type === 'project' ? 'visibility' : 'task'}}</mat-icon>
                View {{result.type | titlecase}}
              </button>
            </div>
          </div>
        </div>

        <!-- No Results Message -->
        <div *ngIf="searchResults.length === 0 && searchForm.get('searchTerm')?.value" 
             class="text-center py-12">
          <mat-icon class="text-gray-300 text-6xl mb-4">search_off</mat-icon>
          <p class="text-gray-500 text-lg">No results found</p>
          <p class="text-gray-400 text-sm mt-2">Try adjusting your search or filters</p>
        </div>
      </div>
    </div>
  </div>
</div>

<div *ngIf="isLoading" class="flex justify-center items-center py-8">
  <mat-spinner diameter="40"></mat-spinner>
</div>

// frontend-react/src/pages/search/Search.tsx
import { useState, useEffect, useCallback } from 'react';
import { Input, Select, Button, Spin, Card } from 'antd';
import { SearchOutlined, FilterOutlined } from '@ant-design/icons';
import { useNavigate } from 'react-router-dom';
import debounce from 'lodash/debounce';
import { searchService } from '../../services/api/searchService';

const { Option } = Select;

interface SearchResult {
  type: 'project' | 'task';
  _id: string;
  name?: string;
  title?: string;
  description: string;
  status?: string;
  priority?: string;
  projectId?: string;
  projectName?: string;
}

interface SearchFilters {
  status: string;
  priority: string;
  type: string;
}

const Search = () => {
  const navigate = useNavigate();
  const [searchTerm, setSearchTerm] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [results, setResults] = useState<SearchResult[]>([]);
  const [isFiltersVisible, setIsFiltersVisible] = useState(false);
  const [filters, setFilters] = useState<SearchFilters>({
    status: '',
    priority: '',
    type: ''
  });

  const statuses = ['Not Started', 'In Progress', 'Stuck', 'Done'];
  const priorities = ['Critical', 'High', 'Medium', 'Low'];
  const types = ['task', 'bug'];

  const performSearch = useCallback(
    debounce(async (term: string, searchFilters: SearchFilters) => {
      if (!term.trim()) {
        setResults([]);
        return;
      }

      try {
        setIsLoading(true);
        const searchResults = await searchService.search(term, searchFilters);
        setResults(searchResults);
      } catch (error) {
        console.error('Search error:', error);
      } finally {
        setIsLoading(false);
      }
    }, 300),
    []
  );

  useEffect(() => {
    performSearch(searchTerm, filters);
    return () => {
      performSearch.cancel();
    };
  }, [searchTerm, filters, performSearch]);

  const handleFilterChange = (key: string, value: string) => {
    setFilters(prev => ({
      ...prev,
      [key]: value
    }));
  };

  const getStatusClass = (status: string): string => {
    switch (status) {
      case 'Not Started': return 'bg-gray-500 text-white';
      case 'In Progress': return 'bg-blue-500 text-white';
      case 'Stuck': return 'bg-red-500 text-white';
      case 'Done': return 'bg-green-500 text-white';
      default: return 'bg-gray-500 text-white';
    }
  };

  const getPriorityClass = (priority: string): string => {
    switch (priority?.toLowerCase()) {
      case 'low': return 'bg-green-500 text-white';
      case 'medium': return 'bg-yellow-500 text-white';
      case 'high': return 'bg-orange-500 text-white';
      case 'critical': return 'bg-purple-500 text-white';
      default: return 'bg-gray-500 text-white';
    }
  };

  return (
    <div className="min-h-screen bg-gray-100 dark:bg-gray-900 p-4 sm:p-6">
      <div className="max-w-4xl mx-auto">
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-sm p-4 sm:p-6">
          {/* Search Header */}
          <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 mb-6">
            <h1 className="text-2xl font-bold text-gray-900 dark:text-gray-100">
              Search
            </h1>
            <Button
              icon={<FilterOutlined />}
              onClick={() => setIsFiltersVisible(!isFiltersVisible)}
              className="self-end"
            >
              Filters
            </Button>
          </div>

          {/* Search Input */}
          <Input
            prefix={<SearchOutlined />}
            placeholder="Search projects and tasks..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="mb-4"
            size="large"
          />

          {/* Filters */}
          {isFiltersVisible && (
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-6 animate-slideDown">
              <Select
                placeholder="Status"
                allowClear
                className="w-full"
                value={filters.status}
                onChange={(value) => handleFilterChange('status', value)}
              >
                {statuses.map(status => (
                  <Option key={status} value={status}>{status}</Option>
                ))}
              </Select>

              <Select
                placeholder="Priority"
                allowClear
                className="w-full"
                value={filters.priority}
                onChange={(value) => handleFilterChange('priority', value)}
              >
                {priorities.map(priority => (
                  <Option key={priority} value={priority}>{priority}</Option>
                ))}
              </Select>

              <Select
                placeholder="Type"
                allowClear
                className="w-full"
                value={filters.type}
                onChange={(value) => handleFilterChange('type', value)}
              >
                {types.map(type => (
                  <Option key={type} value={type}>{type}</Option>
                ))}
              </Select>
            </div>
          )}

          {/* Results */}
          <div className="space-y-4">
            {isLoading ? (
              <div className="flex justify-center py-8">
                <Spin size="large" />
              </div>
            ) : (
              results.map((result) => (
                <Card
                  key={result._id}
                  className="cursor-pointer hover:shadow-md transition-shadow"
                  onClick={() => {
                    if (result.type === 'project') {
                      navigate(`/projects/${result._id}`);
                    } else {
                      navigate(`/projects/${result.projectId}/tasks/${result._id}`);
                    }
                  }}
                >
                  <div className="flex flex-col gap-2">
                    {result.type === 'project' ? (
                      <>
                        <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100">
                          {result.name}
                        </h3>
                        <span className="text-sm text-gray-500">Project</span>
                      </>
                    ) : (
                      <>
                        <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100">
                          {result.title}
                        </h3>
                        <span className="text-sm text-gray-500">
                          Task in {result.projectName}
                        </span>
                        <div className="flex gap-2 mt-2">
                          <span className={`px-2 py-1 rounded-full text-xs ${getStatusClass(result.status!)}`}>
                            {result.status}
                          </span>
                          <span className={`px-2 py-1 rounded-full text-xs ${getPriorityClass(result.priority!)}`}>
                            {result.priority}
                          </span>
                        </div>
                      </>
                    )}
                    {result.description && (
                      <p className="text-gray-600 dark:text-gray-300 line-clamp-2 mt-2">
                        {result.description}
                      </p>
                    )}
                  </div>
                </Card>
              ))
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default Search;
