// frontend/src/app/pages/dashboard/dashboard.component.ts
import { Component, OnInit } from '@angular/core';
import { MatDialog } from '@angular/material/dialog';
import { CreateProjectDialogComponent } from './create-project-dialog/create-project-dialog.component';
import { ProjectService, Project } from '../../services/project.service';
import { MatButtonModule } from '@angular/material/button';
import { MatListModule } from '@angular/material/list';
import { MatMenuModule } from '@angular/material/menu';
import { MatIconModule } from '@angular/material/icon';
import { CommonModule } from '@angular/common';
import { RouterLink, RouterModule } from '@angular/router';
import { EditProjectDialogComponent } from '../project-details/edit-project-dialog/edit-project-dialog.component';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { ConfirmDialogComponent } from '../../shared/confirm-dialog/confirm-dialog.component';
import { AuthService } from '../../services/auth.service';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [
    CommonModule,
    MatButtonModule,
    MatListModule,
    MatMenuModule,
    MatIconModule,
    RouterLink,
    RouterModule,
    EditProjectDialogComponent,
    MatSnackBarModule,
    ConfirmDialogComponent,
    MatProgressSpinnerModule,
  ],
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.css'],
})
export class DashboardComponent implements OnInit {
  createdProjects: Project[] = [];
  memberProjects: Project[] = [];
  isLoading: boolean = false;
  recentProjects: Project[] = [];
  currentUserId: string = '';
  greeting: string = '';
  username: string = '';

  constructor(
    private dialog: MatDialog,
    private projectService: ProjectService,
    private authService: AuthService,
    private snackBar: MatSnackBar
  ) {
    this.currentUserId = this.authService.getCurrentUserId() || '';
    this.username = this.authService.getCurrentUsername() || '';
    this.setGreeting();
  }

  ngOnInit() {
    this.loadUserProjects();
    this.loadRecentProjects();
  }

  private setGreeting(): void {
    const hour = new Date().getHours();
    if (hour < 12) {
      this.greeting = 'Good morning';
    } else if (hour < 18) {
      this.greeting = 'Good afternoon';
    } else {
      this.greeting = 'Good evening';
    }
  }

  loadUserProjects() {
    const currentUserId = this.authService.getCurrentUserId();

    if (!currentUserId) {
      console.error('No user ID found - redirecting to login');
      return;
    }

    this.isLoading = true;
    this.projectService.getUserProjects().subscribe({
      next: (projects: Project[]) => {
        this.createdProjects = projects.filter(project => 
          project.createdBy && project.createdBy._id === currentUserId
        );
        
        this.memberProjects = projects.filter(project => 
          project.createdBy && 
          project.createdBy._id !== currentUserId && 
          project.members?.some(member => member._id === currentUserId)
        );
        this.isLoading = false;
      },
      error: (error) => {
        console.error('Error loading user projects:', error);
        this.snackBar.open('Error loading projects', 'Close', {
          duration: 3000,
        });
        this.isLoading = false;
      },
    });
  }

  loadRecentProjects() {
    this.projectService.getRecentProjects().subscribe({
      next: (projects) => {
        this.recentProjects = projects;
      },
      error: (error) => {
        console.error('Error loading recent projects:', error);
        this.snackBar.open('Error loading recent projects', 'Close', {
          duration: 3000,
        });
      },
    });
  }

  openCreateProjectDialog() {
    const dialogRef = this.dialog.open(CreateProjectDialogComponent, {
      width: '400px',
    });

    dialogRef.afterClosed().subscribe((result) => {
      if (result) {
        this.isLoading = true;
        this.projectService.createProject(result).subscribe({
          next: () => {
            this.loadUserProjects();
            this.snackBar.open('Project created successfully', 'Close', {
              duration: 3000,
            });
          },
          error: (error) => {
            console.error('Error creating project:', error);
            this.snackBar.open('Error creating project', 'Close', {
              duration: 3000,
            });
            this.isLoading = false;
          },
        });
      }
    });
  }

  openEditProjectDialog(project: Project) {
    const dialogRef = this.dialog.open(EditProjectDialogComponent, {
      width: '400px',
      data: { project },
    });
  }

  deleteProject(project: Project) {
    const dialogRef = this.dialog.open(ConfirmDialogComponent, {
      width: '300px',
      data: {
        title: 'Confirm Delete',
        message: `Are you sure you want to delete the project "${project.name}"?`
      }
    });

    dialogRef.afterClosed().subscribe(result => {
      if (result) {
        this.isLoading = true;
        this.projectService.deleteProject(project._id).subscribe({
          next: () => {
            this.loadUserProjects();
            this.snackBar.open('Project deleted successfully', 'Close', {
              duration: 3000,
            });
          },
          error: (error) => {
            console.error('Error deleting project:', error);
            this.snackBar.open('Error deleting project', 'Close', {
              duration: 3000,
            });
            this.isLoading = false;
          },
        });
      }
    });
  }

  editProject(project: Project) {
    const dialogRef = this.dialog.open(EditProjectDialogComponent, {
      width: '300px',
      data: {
        name: project.name,
        description: project.description,
      },
    });

    dialogRef.afterClosed().subscribe((result) => {
      if (result) {
        this.isLoading = true;
        this.projectService.updateProject(project._id, result).subscribe({
          next: (updatedProject) => {
            const index = this.createdProjects.findIndex(
              (p) => p._id === updatedProject._id
            );
            if (index !== -1) {
              this.createdProjects[index] = updatedProject;
            }
            this.loadUserProjects();
            this.snackBar.open('Project updated successfully', 'Close', {
              duration: 3000,
            });
          },
          error: (error) => {
            console.error('Error updating project:', error);
            this.snackBar.open('Error updating project', 'Close', {
              duration: 3000,
            });
            this.isLoading = false;
          },
        });
      }
    });
  }
}

<div class="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100 dark:from-gray-900 dark:to-gray-800">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
    <!-- Greeting Section -->
    <div class="mb-10">
      <h1 class="text-4xl font-bold text-gray-900 dark:text-white mb-2">
        {{ greeting }}, {{ username }}
      </h1>
      <p class="text-gray-600 dark:text-gray-400">Welcome back to your project dashboard</p>
    </div>

    <!-- Loading Spinner -->
    <div *ngIf="isLoading" class="flex justify-center items-center min-h-[400px]">
      <mat-spinner diameter="40"></mat-spinner>
    </div>

    <div *ngIf="!isLoading" class="space-y-10">
      <!-- Recent Projects Section -->
      <div class="bg-white dark:bg-gray-800 rounded-2xl shadow-sm p-6 border border-gray-100 dark:border-gray-700">
        <h2 class="text-2xl font-bold text-gray-900 dark:text-white mb-6">Recently Viewed</h2>
        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          <div *ngFor="let project of recentProjects"
            class="group bg-gray-50 dark:bg-gray-700 rounded-xl p-5 hover:bg-gray-100 dark:hover:bg-gray-600 transition-all duration-300 flex flex-col h-full">
            <div class="flex justify-between items-start mb-3">
              <h3 class="text-lg font-semibold text-gray-900 dark:text-white truncate">{{ project.name }}</h3>
              <span [ngClass]="{
                'bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200': project.createdBy._id === currentUserId,
                'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200': project.createdBy._id !== currentUserId
              }" class="px-3 py-1 rounded-full text-xs font-medium">
                {{ project.createdBy._id === currentUserId ? 'Owner' : 'Member' }}
              </span>
            </div>
            <div class="flex-grow">
              <p class="text-gray-600 dark:text-gray-300 text-sm mb-4 line-clamp-2">{{ project.description }}</p>
            </div>
            <div class="mt-auto pt-4">
              <div class="flex justify-between items-center">
                <div class="flex items-center text-gray-500 dark:text-gray-400 text-sm">
                  <mat-icon class="text-sm mr-1">access_time</mat-icon>
                  <span>{{ project.lastAccessedAt | date:'shortDate' }}</span>
                </div>
                <a [routerLink]="['/projects', project._id]"
                  class="text-blue-600 dark:text-blue-400 hover:text-blue-800 dark:hover:text-blue-300 font-medium text-sm">View →</a>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Your Projects Section -->
      <div class="bg-white dark:bg-gray-800 rounded-2xl shadow-sm p-6 border border-gray-100 dark:border-gray-700 mt-6">
        <div class="flex justify-between items-center mb-6">
          <h2 class="text-2xl font-bold text-gray-900 dark:text-white">Your Projects</h2>
          <button mat-mini-fab color="primary" (click)="openCreateProjectDialog()"
            class="bg-blue-600 hover:bg-blue-700 dark:bg-blue-500 dark:hover:bg-blue-600 shadow-md">
            <mat-icon>add</mat-icon>
          </button>
        </div>
        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          <div *ngFor="let project of createdProjects"
            class="group bg-gray-50 dark:bg-gray-700 rounded-xl p-5 hover:bg-gray-100 dark:hover:bg-gray-600 transition-all duration-300 flex flex-col h-full">
            <div class="flex justify-between items-start mb-3">
              <h3 class="text-lg font-semibold text-gray-900 dark:text-white truncate">{{ project.name }}</h3>
              <div class="opacity-0 group-hover:opacity-100 transition-opacity">
                <button mat-icon-button [matMenuTriggerFor]="menu" class="text-gray-500 hover:text-gray-700">
                  <mat-icon>more_vert</mat-icon>
                </button>
                <mat-menu #menu="matMenu">
                  <button mat-menu-item (click)="editProject(project)">
                    <mat-icon>edit</mat-icon>
                    <span>Edit</span>
                  </button>
                  <button mat-menu-item (click)="deleteProject(project)" class="text-red-600">
                    <mat-icon>delete</mat-icon>
                    <span>Delete</span>
                  </button>
                </mat-menu>
              </div>
            </div>
            <div class="flex-grow">
              <p class="text-gray-600 dark:text-gray-300 text-sm mb-4 line-clamp-2">{{ project.description }}</p>
            </div>
            <div class="mt-auto pt-4">
              <div class="flex justify-between items-center">
                <div class="flex items-center gap-4">
                  <div class="flex items-center text-gray-500 dark:text-gray-400 text-sm">
                    <mat-icon class="text-sm mr-1">group</mat-icon>
                    <span>{{ project.members.length }}</span>
                  </div>
                  <div class="flex items-center text-gray-500 dark:text-gray-400 text-sm">
                    <mat-icon class="text-sm mr-1">calendar_today</mat-icon>
                    <span>{{ project.createdAt | date:'shortDate' }}</span>
                  </div>
                </div>
                <a [routerLink]="['/projects', project._id]"
                  class="text-blue-600 dark:text-blue-400 hover:text-blue-800 dark:hover:text-blue-300 font-medium text-sm">View →</a>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Member Projects Section -->
      <div class="bg-white dark:bg-gray-800 rounded-2xl shadow-sm p-6 border border-gray-100 dark:border-gray-700">
        <div class="flex justify-between items-center mb-6">
          <h2 class="text-2xl font-bold text-gray-900 dark:text-white">Projects You're In</h2>
        </div>
        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          <div *ngFor="let project of memberProjects"
            class="group bg-gray-50 dark:bg-gray-700 rounded-xl p-5 hover:bg-gray-100 dark:hover:bg-gray-600 transition-all duration-300 flex flex-col h-full">
            <div class="flex justify-between items-start mb-3">
              <h3 class="text-lg font-semibold text-gray-900 dark:text-white truncate">{{ project.name }}</h3>
              <span class="bg-green-100 dark:bg-green-900 text-green-800 dark:text-green-200 px-3 py-1 rounded-full text-xs font-medium">
                Member
              </span>
            </div>
            <div class="flex-grow">
              <p class="text-gray-600 dark:text-gray-300 text-sm mb-4 line-clamp-2">{{ project.description }}</p>
            </div>
            <div class="mt-auto pt-4">
              <div class="flex justify-between items-center">
                <div class="flex items-center gap-4">
                  <div class="flex items-center text-gray-500 dark:text-gray-400 text-sm">
                    <mat-icon class="text-sm mr-1">person</mat-icon>
                    <span>{{ project.createdBy.username }}</span>
                  </div>
                  <div class="flex items-center text-gray-500 dark:text-gray-400 text-sm">
                    <mat-icon class="text-sm mr-1">group</mat-icon>
                    <span>{{ project.members.length }}</span>
                  </div>
                </div>
                <a [routerLink]="['/projects', project._id]"
                  class="text-blue-600 dark:text-blue-400 hover:text-blue-800 dark:hover:text-blue-300 font-medium text-sm">View →</a>
              </div>
            </div>
          </div>
        </div>
        <p *ngIf="memberProjects.length === 0" class="text-center text-gray-600 py-8">
          You're not a member of any projects yet.
        </p>
      </div>
    </div>
  </div>
</div>

// frontend-react/src/pages/dashboard/Dashboard.tsx
import { useEffect, useState, useMemo } from "react";
import {
  Card,
  Grid,
  Typography,
  Button,
  Spin,
  Empty,
  message,
  Skeleton,
} from "antd";
import {
  PlusOutlined,
  TeamOutlined,
  FieldTimeOutlined,
} from "@ant-design/icons";
import { useNavigate } from "react-router-dom";
import CreateProjectDialog from "./CreateProjectDialog";
import EditProjectDialog from "./EditProjectDialog";
import ConfirmDialog from "../../components/shared/ConfirmDialog";
import { useTheme } from "../../context/ThemeContext";
import { projectService } from "../../services/api/projectService";
import { useAuth } from "../../hooks/useAuth";
import { useDispatch, useSelector } from "react-redux";
import {
  fetchProjects,
  fetchRecentProjects,
} from "../../store/slices/projectsSlice.ts";
import { RootState } from "../../store/store";

const { Title, Text } = Typography;
const { useBreakpoint } = Grid;

const Dashboard = () => {
  const { isDarkMode } = useTheme();
  const { user, isInitialized } = useAuth();
  const dispatch = useDispatch();
  const navigate = useNavigate();
  const { allProjects, recentProjects, isLoading } = useSelector(
    (state: RootState) => state.projects
  );
  const [createDialogOpen, setCreateDialogOpen] = useState(false);
  const [editDialogOpen, setEditDialogOpen] = useState(false);
  const [confirmDialogOpen, setConfirmDialogOpen] = useState(false);
  const [selectedProject, setSelectedProject] = useState(null);
  const [isUserLoaded, setIsUserLoaded] = useState(false);

  useEffect(() => {
    const token = localStorage.getItem("token");
    if (!token) {
      navigate("/login");
      return;
    }

    // Wait for user data to be available
    if (user?.id) {
      setIsUserLoaded(true);
      dispatch(fetchProjects())
        .unwrap()
        .then((result) => {
          console.log("Fetched Projects:", result);
          dispatch(fetchRecentProjects());
        })
        .catch((error) => {
          console.error("Error loading projects:", error);
          message.error("Failed to load projects");
        });
    }
  }, [dispatch, user?.id, navigate]);

  const createdProjects = useMemo(() => {
    if (!user?.id || !allProjects) return [];

    return allProjects.filter(
      (project) => project?.createdBy?._id.toString() === user.id.toString()
    );
  }, [allProjects, user?.id]);

  const memberProjects = useMemo(() => {
    if (!user?.id || !allProjects) return [];

    return allProjects.filter(
      (project) =>
        project?.createdBy?._id.toString() !== user.id.toString() &&
        project?.members?.some((m) => m?._id.toString() === user.id.toString())
    );
  }, [allProjects, user?.id]);

  const handleCreateProject = async (projectData) => {
    try {
      await projectService.createProject(projectData);
      message.success("Project created successfully");
      dispatch(fetchProjects());
      setCreateDialogOpen(false);
    } catch (error) {
      console.error("Error creating project:", error);
      message.error("Failed to create project");
    }
  };

  const handleEditProject = async (projectData) => {
    try {
      await projectService.updateProject(selectedProject?._id, projectData);
      message.success("Project updated successfully");
      dispatch(fetchProjects());
      setEditDialogOpen(false);
    } catch (error) {
      console.error("Error updating project:", error);
      message.error("Failed to update project");
    }
  };

  const handleDeleteProject = async () => {
    try {
      await projectService.deleteProject(selectedProject?._id);
      message.success("Project deleted successfully");
      dispatch(fetchProjects());
      setConfirmDialogOpen(false);
    } catch (error) {
      console.error("Error deleting project:", error);
      message.error("Failed to delete project");
    }
  };

  const cardClassName = `
    group 
    ${
      isDarkMode
        ? "bg-gray-700 hover:bg-gray-600"
        : "bg-gray-50 hover:bg-gray-100"
    } 
    rounded-xl p-5 
    transition-all duration-300 
    flex flex-col h-full
  `;

  const getGreeting = () => {
    const hour = new Date().getHours();
    if (hour < 12) return "Good morning";
    if (hour < 18) return "Good afternoon";
    return "Good evening";
  };

  const ProjectCard = ({ project, isOwner = false }) => (
    <div className={cardClassName}>
      <div className="flex justify-between items-start mb-3">
        <h3
          className={`text-lg font-semibold truncate ${
            isDarkMode ? "text-white" : "text-gray-900"
          }`}
        >
          {project.name}
        </h3>
        <span
          className={`px-3 py-1 rounded-full text-xs font-medium ${
            isOwner
              ? "bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200"
              : "bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200"
          }`}
        >
          {isOwner ? "Owner" : "Member"}
        </span>
      </div>
      <div className="flex-grow">
        <p
          className={`text-sm mb-4 line-clamp-2 ${
            isDarkMode ? "text-gray-300" : "text-gray-600"
          }`}
        >
          {project.description}
        </p>
      </div>
      <div className="mt-auto pt-4">
        <div className="flex justify-between items-center">
          <div className="flex items-center gap-4">
            <div
              className={`flex items-center text-sm ${
                isDarkMode ? "text-gray-400" : "text-gray-500"
              }`}
            >
              <TeamOutlined className="mr-1" />
              <span>{project.members.length}</span>
            </div>
            <div
              className={`flex items-center text-sm ${
                isDarkMode ? "text-gray-400" : "text-gray-500"
              }`}
            >
              <FieldTimeOutlined className="mr-1" />
              <span>
                {new Date(project.lastAccessedAt).toLocaleDateString()}
              </span>
            </div>
          </div>
          <Button
            type="link"
            onClick={() => navigate(`/projects/${project._id}`)}
            className={`font-medium text-sm ${
              isDarkMode
                ? "text-blue-400 hover:text-blue-300"
                : "text-blue-600 hover:text-blue-800"
            }`}
          >
            View →
          </Button>
        </div>
      </div>
    </div>
  );

  // Create loading cards component
  const LoadingCards = ({ count = 3 }) => (
    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
      {[...Array(count)].map((_, index) => (
        <Card key={index} className={isDarkMode ? "bg-gray-800" : "bg-white"}>
          <Skeleton active paragraph={{ rows: 2 }} />
        </Card>
      ))}
    </div>
  );

  return (
    <div
      className={`min-h-screen ${
        isDarkMode
          ? "bg-gradient-to-br from-gray-900 to-gray-800 text-white"
          : "bg-gradient-to-br from-gray-50 to-gray-100 text-gray-900"
      }`}
    >
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Greeting Section */}
        <div className="mb-10">
          <Title
            level={1}
            className={`text-4xl font-bold mb-2 ${
              isDarkMode ? "text-white" : "text-gray-900"
            }`}
          >
            {getGreeting()}, {user?.username}
          </Title>
          <Text className={isDarkMode ? "text-gray-400" : "text-gray-600"}>
            Welcome back to your project dashboard
          </Text>
        </div>

        {/* Loading State */}
        {isLoading ? (
          <div className="flex justify-center items-center min-h-[400px]">
            <Spin size="large" />
          </div>
        ) : (
          <div className="space-y-10">
            {/* Recently Viewed Section */}
            <div
              className={`rounded-2xl shadow-sm p-6 mb-6 border ${
                isDarkMode
                  ? "bg-gray-800 border-gray-700"
                  : "bg-white border-gray-100"
              }`}
            >
              <Title
                level={2}
                className={isDarkMode ? "text-white" : "text-gray-900"}
              >
                Recently Viewed
              </Title>
              {isLoading ? (
                <LoadingCards count={3} />
              ) : recentProjects.length > 0 ? (
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
                  {recentProjects.map((project) => (
                    <ProjectCard key={project._id} project={project} />
                  ))}
                </div>
              ) : (
                <Empty description="No recent projects" />
              )}
            </div>

            {/* Your Projects Section */}
            <section
              className={`p-6 rounded-xl shadow-sm ${
                isDarkMode
                  ? "bg-gray-800 border border-gray-700"
                  : "bg-white border border-gray-200"
              }`}
            >
              <div className="flex justify-between items-center mb-6">
                <Title
                  level={2}
                  className={isDarkMode ? "text-white" : "text-gray-900"}
                >
                  Your Projects
                </Title>
                <Button
                  type="primary"
                  icon={<PlusOutlined />}
                  onClick={() => setCreateDialogOpen(true)}
                  className="bg-blue-600 hover:bg-blue-700"
                >
                  Create Project
                </Button>
              </div>
              {isLoading ? (
                <LoadingCards />
              ) : createdProjects.length > 0 ? (
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
                  {createdProjects.map((project) => (
                    <ProjectCard
                      key={project._id}
                      project={project}
                      isOwner={true}
                    />
                  ))}
                </div>
              ) : (
                <Empty description="No projects created yet" />
              )}
            </section>

            {/* Projects You're In Section */}
            <div
              className={`rounded-2xl shadow-sm p-6 border ${
                isDarkMode
                  ? "bg-gray-800 border-gray-700"
                  : "bg-white border-gray-100"
              }`}
            >
              <Title
                level={2}
                className={isDarkMode ? "text-white" : "text-gray-900"}
              >
                Projects You're In
              </Title>
              {isLoading ? (
                <LoadingCards count={3} />
              ) : memberProjects.length > 0 ? (
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
                  {memberProjects.map((project) => (
                    <ProjectCard
                      key={project._id}
                      project={project}
                      isOwner={false}
                    />
                  ))}
                </div>
              ) : (
                <Empty description="You're not a member of any projects" />
              )}
            </div>
          </div>
        )}
      </div>

      {/* Dialogs */}
      <CreateProjectDialog
        open={createDialogOpen}
        onClose={() => setCreateDialogOpen(false)}
        onSubmit={handleCreateProject}
        isDarkMode={isDarkMode}
      />
      <EditProjectDialog
        open={editDialogOpen}
        project={selectedProject}
        onClose={() => setEditDialogOpen(false)}
        onSubmit={handleEditProject}
        isDarkMode={isDarkMode}
      />
      <ConfirmDialog
        open={confirmDialogOpen}
        title="Delete Project"
        message={`Are you sure you want to delete "${selectedProject?.name}"?`}
        onConfirm={handleDeleteProject}
        onClose={() => setConfirmDialogOpen(false)}
        isDarkMode={isDarkMode}
      />
    </div>
  );
};

export default Dashboard;
